In [60]:
import pandas as pd
# import matplotlib
# import matplotlib.pyplot as plt
import numpy as np
import time
import requests

def print_full(x):
    with pd.option_context('display.max_columns', None):
        display(x)
def print_all_rows(x):
    with pd.option_context('display.max_rows', None):
        display(x)

## Historical Price Data
* Retrieve from EOD https://eodhistoricaldata.com/
* Not worth doing without paying $80 for a month - then grab it all
* Stick with AV for now, until the other layers have been built - then come back here

* This file should be ready to go - add an API key and start loading... fundamental first then prices


TODO: use the 'from' parameter in the prices call to limit to the range of dates for which fundamental data is available

In [4]:
# EOD API key: 62c0a727bccf89.94027295
#
# Docuemtnation here:
#https://eodhistoricaldata.com/financial-apis/
apikey = '62c0a727bccf89.94027295'


# Functions related to gathering historical price data for lists of tickers
# This will be stored locally and added to on a (fairly) regular basis
# Will make a useful test dataset for prototyping methods for identifying companies to watch
def load_tickerlist():
    data = pd.read_csv('US_LIST_OF_SYMBOLS.csv')
    return data[ data['Exchange'].isin(['NASDAQ','NYSE'])]['Code'].to_list()

# load_tickers_done
# Used to generate the list of tickers already retrieved
# At some point will need to consider merging new data with existing - but for now just fill up one time
def load_fundamentals_done():
    m = pd.read_csv('eod/eod-general.csv', usecols=['ticker'])
    return m['ticker'].to_list()

# Set up an unknown function which will be written in the event that this ticker is unknown
def unknown(t):
    pd.DataFrame([t], columns=['ticker']).to_csv('eod-general.csv', mode='a', header=False)
    return 'unknown'

def load_prices(t):
    t = str.upper(t)
    
    # For testing use the testing ticker and api key
    t = 'MCD'
    apikey = 'demo'
    
    # NOTE: currently grabbing weekly data since I don't need the fine-grain of daily - can change later if needed
    url = f'https://eodhistoricaldata.com/api/eod/{t}.US?api_token={apikey}&period=w'
    print("URL:", url)
    
    # When off the free tier you can request more than one year using &from=1985-09-30
    # Grab the earliest date from the balance sheet data and use that as the from parameter
    
    try:
        csv = pd.read_csv(url, parse_dates=['Date'])
        
        # Need to test out the error handling here - what happens if/when errors occur?
        # For now just generic try/catch and assume otherwise all works ok
        
        # Remove rows that have no valid adjusted_close price - since that's the most useful number
        csv = csv[ csv['Adjusted_close'].notna() ]

        # Radical, but just store adjusted close and volume
        # I don't intend to do technical analysis on daily prices - its just the closing price the rest should be fundamentals
        # If I decide to add this later can always grab it all in one month and add it as a totally separate module
        csv = csv[['Date', 'Adjusted_close','Volume']]
        
    except:
        print('Unknown error in get call')
        return unknown(t)
    
    try:
        csv['ticker'] = t
        return csv
    
    except:
        # two possibilities here - an empty dataset (ok, just empty) or a timeout (return all null, system will check again later)
        return 'timeout'

# data_to_frames
# Accepts a EOD object containing all the fundamental data, overview, earnings and turns into dataframes
# Summary:
# overview = General
# stats = Hightlights + Valuation + SharesStats['SharesOutstanding', 'SharesFloat', 'PercentInsiders', 'PercentInstitutions']
# + Technicals['SharesShort', 'SharesShortPriorMonth', 'ShortRatio', 'ShortPercent'] + SplitsDividends['ForwardAnnualDividendRate', 'ForwardAnnualDividendYield', 'PayoutRatio', 'DividendDate', 'ExDividendDate']
# + AnalystRatings
# earnings = Earnings['reportDate', 'date', 'currency', 'epsActual', 'epsEstimate', 'epsDifference', 'surprisePercent']
# balance_sheet = 
# income_statement = 
# cash_flow = 
# df.index = pd.to_datetime(df.index)
# df.index.rename('quarter', inplace=True)
# df = df[ df.index >= '1990']
# # Convert numeric columns to integer. Doesn't work perfectly but does ok
# #        df = df.apply(pd.to_numeric, errors='ignore', downcast='integer')

def data_to_frames(data):
    
    def select_fields(src, keys):
        return { key:src[key] for key in src.keys() & keys}

    def merge_dicts(src, new):
        return (src.update(new))

    general_fields = [ 'Code', 'Name', 'Exchange', 'CurrencyCode', 'CountryName', 'CountryISO', 'FiscalYearEnd', 'IPODate', 'Sector', 'Industry', 'GicSector','GicGroup','GicIndustry','GicSubIndustry','WebURL','IsDelisted']
    overview_dict = select_fields(data['General'], general_fields)
    ov = pd.DataFrame.from_dict(overview_dict, orient='index').T.rename(columns={'Code':'ticker'}).set_index('ticker')

    shares_fields = ['SharesOutstanding', 'SharesFloat', 'PercentInsiders', 'PercentInstitutions']
    technical_fields = ['SharesShort', 'SharesShortPriorMonth', 'ShortRatio', 'ShortPercent']
    splits_fields = ['ForwardAnnualDividendRate', 'ForwardAnnualDividendYield', 'PayoutRatio', 'DividendDate', 'ExDividendDate']
    stats_dict = data['Highlights']
    merge_dicts(stats_dict, data['Valuation'])
    merge_dicts(stats_dict, select_fields(data['SharesStats'], shares_fields))
    merge_dicts(stats_dict, select_fields(data['Technicals'], technical_fields))
    merge_dicts(stats_dict, select_fields(data['SplitsDividends'], splits_fields))
    merge_dicts(stats_dict, data['AnalystRatings'])
    stats = pd.DataFrame.from_dict(stats_dict, orient='index').T.rename(columns={'MostRecentQuarter':'Quarter'}).set_index('Quarter')

    earnings_dict = data['Earnings']['History']
    earnings = pd.DataFrame.from_dict(data['Earnings']['History'], orient='index').drop(columns=['date']).dropna(axis='columns', how='all')
    earnings = earnings[ earnings['epsActual'].notna() ]
    earnings.rename_axis(index='Quarter')

    bs_dict = data['Financials']['Balance_Sheet']['quarterly']
    bs = pd.DataFrame.from_dict(bs_dict, orient='index').drop(columns=['date']).dropna(axis='columns', how='all')
    bs.rename_axis(index='Quarter')
    inc_dict = data['Financials']['Income_Statement']['quarterly']
    inc = pd.DataFrame.from_dict(inc_dict, orient='index').drop(columns=['date']).dropna(axis='columns', how='all')
    inc.rename_axis(index='Quarter')
    cf_dict = data['Financials']['Cash_Flow']['quarterly']
    cf = pd.DataFrame.from_dict(cf_dict, orient='index').drop(columns=['date']).dropna(axis='columns', how='all')
    cf.rename_axis(index='Quarter')

    return [ov, stats, earnings, bs, inc, cf]

        
# Re-use the earnings function for the other fundamental data
# URL: function=BALANCE_SHEET
# Keys: annualEarnings -> annualReports
def load_fundamentals(t):
    t = str.upper(t)

    # For testing just use the demo URL and ticker AAPL
#     t = 'AAPL'
#     apikey = 'demo'

    # For now assume it will always be a .US exchange so hard-code, but maybe in future this will need to be added...
    url = f'https://eodhistoricaldata.com/api/fundamentals/{t}.US?api_token={apikey}'
    print("URL:", url)

    
    # In case of any errors fetching the data - just return unknown so we ignore this item
    try:
        r = requests.get(url)
        
        # r.status_code of 402 indicates an API error - permissions issue (NOT unknown)
        # In this case maybe time to stop running and figure out why error...
        # 
        if (r.status_code == 402):
            return '402 error'
        data = r.json()

    except:
        print('Unknown error in get call')
        return unknown(t)
    
    print(data.keys())

    # Code up the various errors later once I know how the EOD API works...
    # Timeout returns an Information text
    if ('Information' in data.keys()):
        return 'timeout'

    # Other errors are probably due to some issue with this ticker - drop it
    if ('Error Message' in data.keys()):
        return unknown(t)
    
    if ('General' not in data.keys()):
        return unknown(t)
    
    # We have some data - fornwo assume that if we have 'General' then we have all the others
    [ov, stats, earnings, bs, inc, cf] = data_to_frames(data)
    
    # Add the ticker symbol to frames (ov not needed as it already has the ticker)
    stats['ticker'] = t
    earnings['ticker'] = t
    bs['ticker'] = t
    inc['ticker'] = t
    cf['ticker'] = t
    
    # Slightly different tactic here - directly save the data (append to files) and return a string value
    ov.to_csv('eod/eod-general.csv', mode='a', header=False)
    stats.to_csv('eod/eod-stats.csv', mode='a', header=False)
    earnings.to_csv('eod/eod-earnings.csv', mode='a', header=False)
    bs.to_csv('eod/eod-balancesheet.csv', mode='a', header=False)
    inc.to_csv('eod/eod-incomestatement.csv', mode='a', header=False)
    cf.to_csv('eod/eod-cashflow.csv', mode='a', header=False)

    return t

def load_next_ticker(fulllist=np.nan, tickers_so_far=np.nan):
    if (fulllist is np.nan):
        fulllist = load_tickerlist()
    if (tickers_so_far is np.nan):
        tickers_so_far = pd.read_csv('EOD-prices.csv')['ticker'].unique()
    main_list = np.setdiff1d(fulllist, tickers_so_far)
    print('Tickers remaining:', len(main_list))
    if (len(main_list) == 0):
        return 'DONE'
    return load_prices(main_list[0])

def load_next_fundamentals(alltickers, tickers_done):
    try:
        item = alltickers.pop(0)
        while (item in tickers_done):
            item = alltickers.pop(0)
    except:
        print('*** DONE! ***')
        return "DONE"
    print('Full list:', len(alltickers), '  Tickers so far:', len(tickers_done))
    return load_fundamentals(item)

    
# add_batch_prices: performs ALL the work required to grab some more data
# including reading all the relevant files and saving again...
def add_batch_prices(r=100, r2=5):
    master = load_master()
    alltickers = load_tickerlist()
    for i in range(0,r):
        for j in range(0,r2):
            next_ticker = load_next_ticker(alltickers, master['ticker'].unique() )
            if (type(next_ticker) is str):
                break
            master = pd.concat([master,next_ticker])
        # if not last time through loop then sleep (prevents unneccesary minute wait at the end)
        if (i+1 < r):
            time.sleep(60)
    # moved this line to the end to save poor hard drive from continually re-writing large amounts of data
    # only problem could be if any errors occur before this point the file won't be saved, but it seems quite robust now...
    save_master(master)

# Load the tickerlist_general rather than tickerlist_earnings - uses the master tickerlist to remove unknowns
def add_batch_fundamentals(r=3):
    tickers_done = load_fundamentals_done()
    alltickers = load_tickerlist()
    for i in range(0,r):
        ret = load_next_fundamentals(alltickers, tickers_done)
        print('Ret:', ret)
        if (ret == 'unknown'):
            print('Unknown ticker - stored a blank record')
        elif (ret == 'timeout'):
            print('Timeout - this shouldnt happen wtih EOD...')
        elif (ret == '402 error'):
            print('402: Something wrong, stopping...')
            break;
        else:
            print('Success - ', ret, ' added to tickers_done')
            tickers_done.append(ret)
    print('Batch DONE')

    
# Run it...
#add_batch_fundamentals()

# Testing the prices module
aapl = load_prices('AAPL')
aapl

URL: https://eodhistoricaldata.com/api/eod/MCD.US?api_token=demo&period=w

           Date  Adjusted_close    Volume ticker
0    1966-07-05          0.1434   4179600    MCD
1    1966-07-11          0.1365   1956150    MCD
2    1966-07-18          0.1296   1786050    MCD
3    1966-07-25          0.1259   1251450    MCD
4    1966-08-01          0.1269    753300    MCD
...         ...             ...       ...    ...
2988 2023-10-09        248.3100  15006100    MCD
2989 2023-10-16        258.1100  19385800    MCD
2990 2023-10-23        255.7600  14548500    MCD
2991 2023-10-30        267.8700  21074600    MCD
2992 2023-11-06        267.7900  12841300    MCD

[2993 rows x 4 columns]

In [29]:
# EOD List of tickers
url = f'https://eodhd.com/api/exchange-symbol-list/US?api_token={apikey}&delisted=1&fmt=csv'
print("URL:", url)
    
# Grabbed a copy and stored in eod-symbol_list.csv
csv = pd.read_csv('EOD/eod-symbol-list.csv')

csv

URL: https://eodhd.com/api/exchange-symbol-list/US?api_token=62c0a727bccf89.94027295&delisted=1&fmt=csv

,Code,Name,Country,Exchange,Currency,Type,Isin
0,-P-S,-P-S,USA,NYSE,USD,Preferred Stock,NaN
1,!DJI,TRS DJ Industrial Average PR USD,USA,NaN,USD,Common Stock,NaN
2,00779G392,00779G392,USA,NMFQS,USD,Mutual Fund,NaN
3,0NPP,Koninklijke DSM NV,USA,NaN,USD,Common Stock,NaN
4,1836930D,AMALGAMATED BANK,USA,NaN,USD,Common Stock,NaN
...,...,...,...,...,...,...,...
58840,ZZLLD,ZZLL Information Technology Inc,USA,OTCBB,USD,Common Stock,NaN
58841,ZZPWF,ZZPWF,USA,OTCGREY,USD,Common Stock,NaN
58842,ZZZ,TEST TICKER FOR UTP,USA,NYSE ARCA,USD,Common Stock,NaN
58843,ZZZOD,Zinc One Resources Inc,USA,PINK,USD,Common Stock,NaN
58844,ZZZZQ,ZZZZQ,USA,OTCBB,USD,Common Stock,NaN

In [32]:
# Question: what's the difference between what I just stored (eod-symbol-list.csv) and what was stored ages ago in US_LIST_OF_SYMBOLS.csv) ?
sl = pd.read_csv('EOD/US_LIST_OF_SYMBOLS.csv')
sl

,Code,Name,Country,Exchange,Currency,Type,Isin
0,A,Agilent Technologies Inc,USA,NYSE,USD,Common Stock,US00846U1016
1,AA,Alcoa Corp,USA,NYSE,USD,Common Stock,US0138721065
2,AAA,Listed Funds Trust - AAF First Priority CLO Bo...,USA,NYSE ARCA,USD,ETF,US53656F6566
3,AAAAX,DEUTSCHE REAL ASSETS FUND CLASS A,USA,NMFQS,USD,FUND,NaN
4,AAACX,AAACX,USA,NASDAQ,USD,FUND,NaN
...,...,...,...,...,...,...,...
52757,ZZHGF,ZhongAn Online P & C Insurance Co. Ltd,USA,PINK,USD,Common Stock,NaN
52758,ZZHGY,ZhongAn Online P & C Insurance Co. Ltd,USA,PINK,USD,Common Stock,NaN
52759,ZZLL,ZZLL Information Technology Inc,USA,OTCQB,USD,Common Stock,US98880P2020
52760,ZZZOF,Zinc One Resources Inc,USA,PINK,USD,Common Stock,NaN
52761,3863655,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
slcodes = set(sl['Code'].to_list())
slcodes

csvcodes = set(csv['Code'].to_list())
csvcodes

slcodes

{'DODRW',
 'PTMEY',
 'TNGRF',
 'IGIIX',
 'APIUX',
 'MAFOX',
 'AICYX',
 'PDSKX',
 'CULRX',
 'PXTIX',
 'PBCO',
 'BSX-PA',
 'NABIX',
 'FIIUX',
 'RMAX',
 'TRS',
 'HMXAX',
 'AGMH',
 'RKGXF',
 'SAFT',
 'DBEU',
 'WAIOX',
 'WMSCX',
 'WISIX',
 'CECPX',
 'CTTLX',
 'CBDX',
 'IGOV',
 'NXHSF',
 'PRAY',
 'KEYR',
 'SMID',
 'RELY',
 'CIZ',
 'INFRX',
 'CAGXX',
 'MRGCX',
 'UEXCF',
 'IAMOX',
 'TVIXF',
 'PSA-P-H',
 'CTTAF',
 'CUIRF',
 'NSRIX',
 'DVFTX',
 'PLTJX',
 'FTGLX',
 'LGRXX',
 'MLVAX',
 'MRSRX',
 'FIKCX',
 'HARXX',
 'HLDTX',
 'WDH',
 'RMYHY',
 'MYE',
 'CHSH',
 'ASXDX',
 'PARHX',
 'FIONX',
 'LIHKX',
 'ACIOX',
 'RRBGX',
 'VWLTX',
 'VSTSX',
 'TCBRX',
 'HDB',
 'PSNY',
 'CGOCX',
 'EITMX',
 'AGVYX',
 'UMCVX',
 'WELX',
 'ALORY',
 'BAK',
 'SCPPF',
 'JLJHX',
 'HAGHY',
 'BTCMX',
 'FMAO',
 'ALCCX',
 'DCF',
 'FMCEX',
 'UNRV',
 'GRPTF',
 'RYALX',
 'TIRRX',
 'XBJL',
 'PTEL',
 'OIERX',
 'JCRAX',
 'HADRX',
 'THOGF',
 'BNOV',
 'OSCUF',
 'SHW',
 'FCLKX',
 'CMOMX',
 'GTRCX',
 'MDBRX',
 'ACOGF',
 'SNTFX',
 'TNMRX',
 'WAAXX',
 'TLRY',
 'NBRY',
 'FNVTU',
 'JSNSF',
 'KNBWF',
 'FLOOF',
 'PSMJ',
 'TWO-P-B',
 'VMFRX',
 'PLBC',
 'ASRLX',
 'NRSNW',
 'CSOC',
 'SHGP',
 'WAURX',
 'LVOXW',
 'EQLIX',
 'ADSIX',
 'PKWY',
 'FPACX',
 'ITAQU',
 'GRRGX',
 'INFXX',
 'OEQAX',
 'CSEIX',
 'GARPF',
 'JNMCX',
 'MTBAX',
 'CPCCX',
 'SVSN',
 'WSSCX',
 'EMBH',
 'JLIGX',
 'NVMLF',
 'ARBTF',
 'AVGNX',
 'TDSC',
 'BCAKX',
 'ZPTAF',
 'GRRPX',
 'DFFIX',
 'EAGG',
 'DVSPF',
 'RETDF',
 'DFLEX',
 'JFNNX',
 'SKBSY',
 'PBLCX',
 'SRHBF',
 'TENG',
 'CGLGX',
 'CEM',
 'EXPL',
 'IDOG',
 'PGRU',
 'FBBTX',
 'CSIBX',
 'EILGX',
 'ASGI',
 'DTGI',
 'HYCAX',
 'DMCFX',
 'AHYLX',
 'BOBIX',
 'MSUMX',
 'SLVDF',
 'RAIN',
 'ETIHX',
 'LPJIX',
 'TNHRX',
 'NXTYQ',
 'CNRR',
 'BNDX',
 'DMBCX',
 'APH',
 'AUNYX',
 'MSAAX',
 'FBBHX',
 'JCNTX',
 'MITFF',
 'NEOM',
 'NNWWF',
 'CSGCX',
 'MLPH',
 'SLAFX',
 'DKNG',
 'MMRZX',
 'PRSNF',
 'ACCFF',
 'RKHNF',
 'ADGYX',
 'BBLC',
 'ADNIX',
 'JNYAX',
 'TBIWX',
 'CSCRX',
 'INFU',
 'BRRXX',
 'JRSSX',
 'NMPAX',
 'OSOL',
 'RIET',
 'SSHVX',
 'GSEUX',
 'AFCSX',
 'JLKQX',
 'PDHVX',
 'ECBAX',
 'TWO',
 'HIGUX',
 'PLUDX',
 'PCVX',
 'CINV',
 'FNVTW',
 'TIPT',
 'QRHC',
 'EXPGY',
 'PTRQX',
 'JFARX',
 'SOUCX',
 'PINLX',
 'MNXBF',
 'LVGI',
 'CFRHF',
 'LCTRX',
 'FLWBF',
 'INCPF',
 'JLGPX',
 'DAVA',
 'CNVVF',
 'NPCE',
 'BAUFF',
 'ARCNF',
 'IMCB',
 'LEOVF',
 'LEDS',
 'DABLX',
 'VRHYX',
 'JEVCX',
 'TVSVX',
 'FZSMZX',
 'FRFXX',
 'TCWIX',
 'MBCI',
 'BFGX',
 'HCIEX',
 'IEUR',
 'ECOX',
 'EPLKX',
 'TCPAX',
 'SNCVF',
 'TYG',
 'MRBK',
 'FDD',
 'GHYMX',
 'FITLX',
 'FTWDFX',
 'NCXS',
 'TWUSX',
 'CNAF',
 'PMIFX',
 'EEMPX',
 'FRISX',
 'FWP',
 'MNXMF',
 'STSGX',
 'MGTCX',
 'SIECX',
 'MARK',
 'BFAM',
 'GPPAX',
 'TTAC',
 'TSILX',
 'RHHTX',
 'MXI',
 'CRCQW',
 'CRCSX',
 'VALLX',
 'XBTAX',
 'GSXAX',
 'TCWCX',
 'SCHD',
 'ESFAX',
 'PFFDX',
 'XPAXU',
 'ETACW',
 'OCTZ',
 'PSYK',
 'TRCLX',
 'SGAPY',
 'JMPHF',
 'FFNIX',
 'ZVIA',
 'CAIRX',
 'FPZXX',
 'ARCAY',
 'JDPAX',
 'FSNOX',
 'JHRGX',
 'XYLTF',
 'TIPX',
 'RYDHX',
 'GAOAX',
 'FOEFOX',
 'HYZNW',
 'FALAX',
 'GXXY',
 'MKSXX',
 'TRBCX',
 'AMANF',
 'EIVIX',
 'MEMI',
 'NMHAX',
 'EICCX',
 'MAA-PI',
 'AFBOF',
 'DSUS',
 'EEMO',
 'DCAIX',
 'VYSGX',
 'MNEAX',
 'FFMGF',
 'SFFYF',
 'QMDT',
 'GPDNF',
 'DURA',
 'PEQKX',
 'SWKH',
 'SNORX',
 'GGBZX',
 'FITRX',
 'WLGYX',
 'MEVOX',
 'NWALX',
 'PLUS',
 'DTCXX',
 'FDSWX',
 'CSXCX',
 'GTYHW',
 'MGQAX',
 'ERH',
 'FIW',
 'FSIXX',
 'RIRAX',
 'SCPUX',
 'NSHBY',
 'DARXX',
 'RNMBF',
 'VIDAX',
 'FSYCX',
 'LNXGF',
 'CLCS',
 'FSEOX',
 'AMBA',
 'FEDTX',
 'IFZZF',
 'QLMAEX',
 'TTIHX',
 'BDFFX',
 'RBACX',
 'BOB',
 'PXWGX',
 'TQPYX',
 'ELSLF',
 'CWST',
 'FDTFX',
 'VAPR',
 'ESAGX',
 'CENQW',
 'CGRCX',
 'KLGDF',
 'FGVXX',
 'FFIJX',
 'PIPIX',
 'AUNTX',
 'ERFB',
 'NWJIX',
 'MWHYX',
 'SSKN',
 'HBMCX',
 'TABYX',
 'BIDU',
 'LGLRX',
 'FTWS',
 'NLSIX',
 'CMLFX',
 'MOO',
 'TNSGF',
 'FCSPX',
 'NWHBX',
 'SSBRX',
 'EVFCX',
 'EDXC',
 'JBAFX',
 'HRCCX',
 'CKHUY',
 'GBCIX',
 'IKMA',
 'TGVYX',
 'BOSCX',
 'JHMT',
 'BRVVF',
 'SOS',
 'ELTP',
 'ARTM',
 'FDBIX',
 'JLKZX',
 'SOHOF',
 'PKRCX',
 'TTEK',
 'PJFOX',
 'PTHIF',
 'ALVIX',
 'CHAU',
 'VGLIX',
 'SALRY',
 'CHFTX',
 'GGN-PB',
 'HMVJX',
 'MDMN',
 'JPORX',
 'XAWPX',
 'AVLP',
 'INGP',
 'CCSAX',
 'SWQRX',
 'IMWAX',
 'TEVA',
 'BIB',
 'NRBAX',
 'ORINF',
 'DEUIX',
 'MKHCX',
 'WRMA',
 'MACMX',
 'FWOZX',
 'NWMAX',
 'ELRFF',
 'JVAYX',
 'HAIL',
 'KGC',
 'SHPAX',
 'EVSV',
 'STNABX',
 'IHSIX',
 'NPTH',
 'CCPUF',
 'VLT',
 'LRFC',
 'MMNFF',
 'NMNSF',
 'CCRV',
 'HFAIX',
 'MPZSX',
 'WFENX',
 'FHAPX',
 'LTTHF',
 'LSRCX',
 'AGM-P-D',
 'GPOVY',
 'NLSN',
 'BNGE',
 'IYPOX',
 'FFGAX',
 'PQIPX',
 'PAM',
 'TFIPX',
 'APPHW',
 'TRBOX',
 'SBFIX',
 'APAM',
 'PRTHW',
 'ENJ',
 'RNHIX',
 'VNYTX',
 'XTTXF',
 'VGLRX',
 'PLGIX',
 'TRLZX',
 'MTXRX',
 'PEGRU',
 'HWSCX',
 'DNAC',
 'CPUCX',
 'MCEFX',
 'CATVX',
 'HTOXX',
 'AHT-PF',
 'DPRRX',
 'JGERX',
 'JVSNX',
 'KJFI',
 'BLKC',
 'EIPAF',
 'HDVIX',
 'LVHI',
 'RBHHX',
 'FLGEX',
 'FOKUX',
 'TSNIX',
 'FHLSX',
 'JMGPX',
 'TFZI',
 'TQMIX',
 'RGECX',
 'NWL',
 'CLBFX',
 'VETTF',
 'WWNTF',
 'ZLPSF',
 'RMUYX',
 'HDMV',
 'PMTXX',
 'IWAL',
 'FMTZX',
 'VEJID',
 'NNVC',
 'JMABX',
 'PEFIX',
 'RZREF',
 'SLADX',
 'VWTWX',
 'TQSAX',
 'IASTX',
 'IPXHF',
 'HDRPF',
 'QBDAX',
 'NBRRX',
 'PCPDF',
 'PICB',
 'JCBRX',
 'SSCKX',
 'FOKZX',
 'TRDF',
 'BOFIX',
 'BSGRX',
 'ZINGW',
 'FIASX',
 'FLGYOX',
 'MTR',
 'APHTF',
 'CNTAX',
 'FLUVX',
 'FPQYCX',
 'BIAPX',
 'EAUSF',
 'MSHLX',
 'MTW',
 'TIBNX',
 'TUXS',
 'VTRNX',
 'FLSPX',
 'JINFF',
 'VLDRX',
 'PAIMX',
 'BKPIX',
 'FLERX',
 'AKBTY',
 'ARWIX',
 'TDECX',
 'IUS',
 'AXLE',
 'CLYYF',
 'FNB-PE',
 'CQTRX',
 'JNARX',
 'LQISX',
 'VPER',
 'TSCIX',
 'TBCPW',
 'ISQAX',
 'REFR',
 'BBTSX',
 'GTVEX',
 'CSIZX',
 'YWRLF',
 'NWXHX',
 'CLOFX',
 'RPXIX',
 'ANDVX',
 'AIPG',
 'NIQAX',
 'CMDRX',
 'BCNN',
 'GDGIX',
 'WONDF',
 'UJPSX',
 'FBLAX',
 'BJINF',
 'DUTV',
 'FDEKX',
 'FMCCO',
 'FRIIF',
 'FNORX',
 'HSVRX',
 'TRZOX',
 'VPTV',
 'AWSI',
 'GBRSF',
 'FKCJRX',
 'ARGYX',
 'LEMIF',
 'VSEAX',
 'JABYX',
 'GNHRF',
 'BTAXX',
 'SSAZX',
 'DLNG-PA',
 'IYMIX',
 'NCRBF',
 'TFEQX',
 'QDVSX',
 'PLARX',
 'AAGFF',
 'GFOF',
 'MDOCX',
 'ESMYX',
 'TUIFY',
 'MRZLF',
 'TKFHY',
 'MNWTX',
 'TOTTX',
 'VSQRX',
 'GQLVX',
 'HPX',
 'LIWKX',
 'LYJN',
 'MCGIX',
 'HAZH',
 'HLMVX',
 'NXPL',
 'RWRDP',
 'HIOIX',
 'SSEIX',
 'PBMPX',
 'HGHRX',
 'TGRIX',
 'CHKMF',
 'MCRNF',
 'FLRHX',
 'HFLIX',
 'CID',
 'APPDW',
 'PBKC',
 'SLNX',
 'KCDMY',
 'BNS',
 'LEGAW',
 'EELDX',
 'BLGI',
 'FMNEX',
 'CCGTX',
 'AUIAX',
 'CBAEX',
 'CEGGX',
 'ELPKF',
 'OMQS',
 'VRTV',
 'ESWW',
 'GICPX',
 'HORIW',
 'HELFY',
 'NLGAX',
 'PG',
 'OCIO',
 'PCBSX',
 'PBRNX',
 'VINS',
 'ISGIF',
 'EMAX',
 'MOTE',
 'MPLSTX',
 'XMHNX',
 'CIPAX',
 'BALAPX',
 'SWOBX',
 'TALRX',
 'FQMQQX',
 'KNDYF',
 'PBBZX',
 'TEGRX',
 'FCEL',
 'FBSBF',
 'CFIV',
 'NHMRX',
 'PLIDX',
 'ICCIX',
 'SWDHY',
 'CNF',
 'PMNPX',
 'CAPE',
 'FTHI',
 'HMJIX',
 'ACIO',
 'JAGR',
 'ASLGX',
 'ELCRX',
 'HNI',
 'GDRZF',
 'SPDW',
 'BKMIX',
 'GCMRX',
 'TOLWF',
 'RYUTX',
 'BFPXX',
 'LIMAX',
 'TDEAX',
 'UMGNF',
 'GGSIX',
 'LIFAX',
 'LNSR',
 'YUMAQ',
 'FCFIX',
 'JAENX',
 'GCTK',
 'THRN',
 'VLAGX',
 'URE',
 'TOTXX',
 'KMDVX',
 'ONXYY',
 'NHTC',
 'GSJY',
 'PXMAX',
 'DSIBX',
 'EVRRF',
 'TYDEV',
 'TCREX',
 'IASSX',
 'BOSOX',
 'AFDGX',
 'FIZOMX',
 'GAKAX',
 'LTSF',
 'SRIFX',
 'ISARF',
 'IRIDQ',
 'RIFIX',
 'JHYAX',
 'EICAX',
 'LNJIX',
 'XIN',
 'THCX',
 'IGR',
 'ELDN',
 'IFRWX',
 'UBEOF',
 'VWVMX',
 'CSASF',
 'ASPN',
 'BLQC',
 'JHTCX',
 'IGEN',
 'CSMOX',
 'MLSYY',
 'FUNL',
 'SMWCF',
 'JRYPX',
 'FEBZ',
 'CSGEF',
 'LGVCW',
 'APA',
 'INDCX',
 'TASCX',
 'HMPT',
 'PLVIX',
 'BSIKX',
 'IDXIX',
 'CDAQW',
 'SKYU',
 'IVRSX',
 'PHLCX',
 'PMGRX',
 'CEAD',
 'ASGHX',
 'HURC',
 'TTNDF',
 'ESSI',
 'EMLDU',
 'SHIAX',
 'WBIIX',
 'NIABY',
 'TTRHF',
 'MSVB',
 'SHO-PI',
 'JLKHX',
 'ADGIX',
 'CROOF',
 'OTRGX',
 'GITSX',
 'NVO',
 'PMFMX',
 'EDF',
 'RSDQX',
 'XNROX',
 'MGRD',
 'FCOQX',
 'IOIOF',
 'SANJF',
 'RZV',
 'SKRJ',
 'PERT',
 'HBBHF',
 'UNIEF',
 'IDCBY',
 'MMWGX',
 'BSCXX',
 'FCSRX',
 'TDIFX',
 'OCAX',
 'AEDFX',
 'VITSX',
 'FSMDX',
 'ABLSX',
 'RSPACX',
 'NEZNX',
 'TRRFF',
 'MCBZX',
 'CPROF',
 'XOM',
 'JHEIX',
 'WPSIX',
 'CDJM',
 'AWSHX',
 'MMKNX',
 'PAUCX',
 'WARR',
 'WFJXX',
 'FTAELX',
 'GLLIU',
 'HYCCX',
 'MXBOX',
 'DOGMX',
 'AXVEF',
 'VITFF',
 'SCX',
 'MNOCX',
 'BEMVX',
 'DCUCX',
 'IQLT',
 'BCOW',
 'DGRE',
 'PCWRX',
 'WRNXX',
 'SMRVF',
 'KMDCX',
 'IOVCX',
 'FCYXX',
 'CMOEX',
 'IVLC',
 'LGBUX',
 'ISPFF',
 'TWGGX',
 'BTTRX',
 'AMAX',
 'FRONW',
 'EFO',
 'CBARX',
 'FLQL',
 'GCMDX',
 'BNIGF',
 'BLV',
 'HISFX',
 'NHICX',
 'AIFBX',
 'FGJWPX',
 'OPTBF',
 'XAVKX',
 'VHCIX',
 'MEDOF',
 'PTIPX',
 'VIGTX',
 'KMFI',
 'EBSFX',
 'PRIDX',
 'RIMHX',
 'ESGMX',
 'PKRTX',
 'SRLP',
 'DMHIX',
 'ALTUW',
 'SPDRF',
 'RELVX',
 'PTYIX',
 'MAPPX',
 'LTFOX',
 'ACSCX',
 'WHLRL',
 'QGMIX',
 'XMPAX',
 'ZGN',
 'TARBX',
 'BROS',
 'PLJMX',
 'GS-PK',
 'FWATX',
 'ECCAX',
 'ILGJX',
 'FHN-PC',
 'PCOXX',
 'SPNT',
 'IPHYF',
 'FACGX',
 'NSDVX',
 'SVNBY',
 'SHACU',
 'PPVIX',
 'PQICX',
 'FDFZX',
 'PSA-PH',
 'IFLXF',
 'SHOFF',
 'CADFX',
 'LPDIX',
 'PYTCY',
 'DTARF',
 'PSA-PN',
 'RYMZX',
 'TSDLX',
 'HUMDX',
 'HALMY',
 'VISTX',
 'ANCMX',
 'FRBAX',
 'JNSPX',
 'PTREX',
 'JJGTF',
 'VEON',
 'JSOCX',
 'SLN',
 'LYFT',
 'JUMT',
 'ILIM',
 'WHGHX',
 'CP',
 'EQNIX',
 'XCRP',
 'BRKR',
 'FSLUF',
 'BEOB',
 'PBCBF',
 'FUNCX',
 'HOM',
 'DODIX',
 'FFBQX',
 'SWFCX',
 'NCOIX',
 'DNB',
 'PLHCF',
 'PRYMF',
 'IBOC',
 'IJSTX',
 'TSUSF',
 'ISHAX',
 'MXECX',
 'PSKOF',
 'FCGXX',
 'QUOT',
 'BTO',
 'HUML',
 'PFNL',
 'WFCFX',
 'JKE',
 'ASICX',
 'MXGTX',
 'CLCFF',
 'OPIGX',
 'PCILF',
 'TPII',
 'TRNX',
 'HAWLM',
 'PDLEX',
 'BRKHU',
 'ESGFF',
 'MBLDX',
 'FOGCF',
 'VEL',
 'CJNHF',
 'VWTJX',
 'ASLE',
 'TVRVX',
 'INFIX',
 'FKYCFX',
 'FPRAEX',
 'CLABF',
 'MMIEX',
 'MFQAX',
 'MIDE',
 'VNVCX',
 'CVGCX',
 'JETAX',
 'ABASX',
 'XVV',
 'MSBRX',
 'CODAF',
 'FLFIX',
 ...}

In [56]:
# Well, that's weird...
# Seems that these two files contain almost completely different codes ???
for code in sl['Code'][0:10]:
    print(code)
    print(csv[ csv['Code'] == code])

A
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []
AA
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []
AAA
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []
AAAAX
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []
AAACX
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []
AAAEX
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []
AAAFX
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []
AAAGX
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []
AAAHX
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []
AAAIX
Empty DataFrame
Columns: [Code, Name, Country, Exchange, Currency, Type, Isin]
Index: []

In [61]:
print_all_rows(csv.head(n=200))

,Code,Name,Country,Exchange,Currency,Type,Isin
0,-P-S,-P-S,USA,NYSE,USD,Preferred Stock,NaN
1,!DJI,TRS DJ Industrial Average PR USD,USA,NaN,USD,Common Stock,NaN
2,00779G392,00779G392,USA,NMFQS,USD,Mutual Fund,NaN
3,0NPP,Koninklijke DSM NV,USA,NaN,USD,Common Stock,NaN
4,1836930D,AMALGAMATED BANK,USA,NaN,USD,Common Stock,NaN
5,1885708D,MEREDITH HOLDINGS CORP,USA,NaN,USD,Common Stock,NaN
6,1922527D,TRINSEO PLC,USA,NaN,USD,Common Stock,NaN
7,1MSF,1MSF,USA,NaN,USD,Common Stock,NaN
8,202K1,S K1 Cbot Soybean Futures May 2021,USA,NaN,USD,Common Stock,NaN
9,2104381D,SINTX TECHNOLOGIES INC,USA,NaN,USD,Common Stock,NaN
10,2178883D,ZYMEWORKS DELAWARE INC,USA,NaN,USD,Common Stock,NaN
11,30326F720,30326F720,USA,NMFQS,USD,Mutual Fund,NaN
12,46147E460,46147E460,USA,NMFQS,USD,Mutual Fund,NaN
13,4BRZ,4BRZ,USA,NaN,USD,Common Stock,NaN
14,4GLD,Xetra-Gold,USA,NaN,USD,Common Stock,NaN
15,6I4,6I4,USA,NaN,USD,Common Stock,NaN
16,8TRA,Traton SE,USA,NaN,USD,Common Stock,NaN
17,9CI,9CI,USA,NaN,USD,Common Stock,NaN
18,A-P-DM,A-P-DM,USA,OTCBB,USD,Preferred Stock,NaN
19,A-P-DN,A-P-DN,USA,OTCBB,USD,Preferred Stock,NaN
20,A-P-DO,A-P-DO,USA,OTCBB,USD,Preferred Stock,NaN
21,A-P-DP,A-P-DP,USA,OTCBB,USD,Preferred Stock,NaN
22,A17U,A17U,USA,NaN,USD,Common Stock,NaN
23,A200,A200,USA,NaN,USD,Common Stock,NaN
24,A2A,A2A,USA,NaN,USD,Common Stock,NaN
25,A5G,A5G,USA,NaN,USD,Common Stock,NaN
26,A6AG0,Light Sweet Crude Oil (Nymex Wti Futures 2004,USA,NaN,USD,Common Stock,NaN
27,A6AZ1,Light Sweet Crude Oil (Nymex Wti Futures 2111,USA,NaN,USD,Common Stock,NaN
28,AA-W,AA-W,USA,NYSE,USD,Common Stock,NaN
29,AAAB,Admiralty Bancorp Inc,USA,NASDAQ,USD,Common Stock,NaN
30,AAADX,ALPINE RISING DIVIDEND FUND CLASS A,USA,NMFQS,USD,FUND,NaN
31,AAAGE,AAA CENTURY GROUP USA INC,USA,US,USD,Common Stock,NaN
32,AAAGY,Altana Aktiengesellschaft,USA,NYSE,USD,Common Stock,NaN
33,AAAID,AAAID,USA,PINK,USD,Common Stock,NaN
34,AAAIF,Alternative Investment Trust,USA,PINK,USD,FUND,NaN
35,AAALF,Aareal Bank AG,USA,PINK,USD,Common Stock,NaN
36,AAAP,Advanced Accelerator Applications S.A,USA,NASDAQ,USD,Common Stock,US00790T1007
37,AAARF,Aluar Aluminio Argentino S.A.I.C,USA,OTCGREY,USD,Common Stock,NaN
38,AAAWX,DEUTSCHE REAL ASSETS FUND CLASS T,USA,NMFQS,USD,FUND,NaN
39,AAB,Astrazeneca Ab,USA,NYSE,USD,Common Stock,NaN
40,AABA,Altaba Inc,USA,NASDAQ,USD,Common Stock,US0213461017
41,AABAX,ACTIVE CORE FUND CLASS A,USA,NMFQS,USD,FUND,NaN
42,AABC,Access Anytime Bancorp Inc,USA,NASDAQ,USD,Common Stock,NaN
43,AABDX,AMERICAN BEACON INTERMEDIATE BOND FUND INSTITU...,USA,NMFQS,USD,FUND,NaN
44,AABNF,ALTIN AG BAAR NAMEN,USA,PINK,USD,Common Stock,NaN
45,AABNX,AMERICAN BEACON BALANCED FUND AMR CLASS,USA,NMFQS,USD,FUND,NaN
46,AABSX,ALLIANZGI BEST STYLES EMERGING MARKETS EQUITY ...,USA,NMFQS,USD,FUND,NaN
47,AABUX,ALLIANZGI BEST STYLES U.S. EQUITY FUND CLASS A,USA,NMFQS,USD,FUND,NaN
48,AAC_old,AAC Holdings Inc,USA,NYSE,USD,Common Stock,US0003071083
49,AAC1,Arcadia Financial Ltd,USA,NYSE,USD,Common Stock,NaN
50,AACB,Alliance Atlantis Communications Inc,USA,NASDAQ,USD,Common Stock,NaN
51,AACBX,ACTIVE CORE FUND CLASS C,USA,NMFQS,USD,FUND,NaN
52,AACC,Asset Acceptance Capital Corp,USA,NASDAQ,USD,Common Stock,NaN
53,AACE,Ace Cash Express Inc,USA,NASDAQ,USD,Common Stock,NaN
54,AACEU,AACEU,USA,NYSE,USD,Common Stock,NaN
55,AACEX,MULTI CAP EQUITY INCOME FUND CLASS C,USA,NMFQS,USD,FUND,NaN
56,AACEY,Asia Cement (China) Holdings Corporation,USA,PINK,USD,Common Stock,NaN
57,AACH,AAC Holdings Inc,USA,PINK,USD,Common Stock,NaN
58,AACIX,AMERICAN BEACON MID-CAP VALUE FUND INSTITUTION...,USA,NMFQS,USD,FUND,US02368A3150
59,AACMF,AACMF,USA,OTCMKTS,USD,Common Stock,NaN
60,AACOU,Advancit Acquisition Corp. I,USA,NASDAQ,USD,Common Stock,NaN
61,AACPF,Australia Acquisition Corp (Foreign),USA,OTCBB,USD,Common Stock,NaN
62,AACPU,AACPU,USA,NASDAQ,USD,Common Stock,NaN
63,AACQ,Origin Materials Inc,USA,NASDAQ,USD,Common Stock,US68622D1063
64,AACQU,Origin Materials Inc,USA,NASDAQ,USD,Common Stock,KY04316G2048
65,AACQW,Artius Acquisition Inc,USA,NASDAQ,USD,Common Stock,KY04316G1131
66,AACT_old,Ares Acquisition Corporation II,USA,NYSE,USD,Common Stock,NaN
67,AACYX,ALGER MID CAP FOCUS FUND ALGER MID CAP FOCUS F...,USA,NMFQS,USD,FUND,NaN
68,AADDX,ALPINE RISING DIVIDEND FUND INSTITUTIONAL CLASS,USA,NMFQS,USD,FUND,NaN
69,AADGX,AASGARD DIVIDEND GROWTH SMALL & MID-CAP FUND N...,USA,NMFQS,USD,FUND,NaN
70,AADV,AADV,USA,NASDAQ,USD,Common Stock,NaN
71,AADXX,AADXX,USA,NMFQS,USD,Mutual Fund,NaN
72,AAEBX,INVESCO GROWTH ALLOCATION FUND CLASS B,USA,NMFQS,USD,FUND,NaN
73,AAEED,Altair Resources Inc,USA,OTCMKTS,USD,Common Stock,NaN
74,AAEH,Core Lithium Corp,USA,PINK,USD,Common Stock,NaN
75,AAEHD,All American Energy Corp,USA,PINK,USD,Common Stock,NaN
76,AAEPX,AMERICAN BEACON EMERGING MARKETS FUND INVESTOR...,USA,NMFQS,USD,FUND,NaN
77,AAEQX,MULTI CAP EQUITY INCOME FUND CLASS A,USA,NMFQS,USD,FUND,NaN
78,AAEXX,AAEXX,USA,NMFQS,USD,Mutual Fund,NaN
79,AAEYX,AAEYX,USA,NMFQS,USD,Mutual Fund,NaN
80,AAF,American Government Income Portfolio Inc,USA,NYSE,USD,Common Stock,NaN
81,AAFGF,AAFGF,USA,OTCGREY,USD,Common Stock,NaN
82,AAFPX,AMERICAN BEACON S&P 500 INDEX FUND INVESTOR CLASS,USA,NMFQS,USD,FUND,NaN
83,AAGAX,AMERICAN BEACON LARGE CAP VALUE FUND AMR CLASS,USA,NMFQS,USD,FUND,NaN
84,AAGGY,AAGGY,USA,OTCGREY,USD,Common Stock,NaN
85,AAGIY1,Anglo American Gold Investment Co Ltd,USA,NASDAQ,USD,Common Stock,NaN
86,AAGR,AAGR,USA,NASDAQ,USD,Common Stock,NaN
87,AAGRX,FORWARD AGGRESSIVE GROWTH ALLOCATION FUND INST...,USA,NMFQS,USD,FUND,NaN
88,AAH,AAH,USA,NYSE,USD,Common Stock,NaN
89,AAHIF,Asahi Co. Ltd,USA,PINK,USD,Common Stock,NaN
90,AAI,AIRTRAN HOLDINGS INC,USA,NYSE,USD,Common Stock,US00949P1084
91,AAI1,Aqua Alliance Inc,USA,NYSE MKT,USD,Common Stock,NaN
92,AAIAX,AMERICAN BEACON INTERNATIONAL EQUITY FUND AMR ...,USA,NMFQS,USD,FUND,NaN
93,AAIFX,CROW POINT ALTERNATIVE INCOME FUND CROW POINT ...,USA,NMFQS,USD,FUND,NaN
94,AAII,Aaipharma Inc,USA,NASDAQ,USD,Common Stock,NaN
95,AAINF,AsiaBaseMetals Inc,USA,OTCGREY,USD,Common Stock,NaN
96,AAIR,Avantair Inc,USA,PINK,USD,Common Stock,US00949P1084
97,AAIRE,AVANTAIR INC,USA,US,USD,Common Stock,NaN
98,AAIRX,AAIRX,USA,NMFQS,USD,Mutual Fund,NaN
99,AAIT,iShares MSCI All Country Asia Info Tech,USA,NASDAQ,USD,ETF,NaN
100,AAIYX,ALGER MID CAP FOCUS FUND ALGER MID CAP FOCUS F...,USA,NMFQS,USD,FUND,NaN
101,AAK,AAK AB,USA,NaN,USD,Common Stock,NaN
102,AALB,Aalberts NV,USA,NaN,USD,Common Stock,NaN
103,AALIX,ASTON/HERNDON LARGE CAP VALUE FUND CLASS N SHARES,USA,NMFQS,USD,FUND,NaN
104,AALPX,AMERICAN BEACON SHORT-TERM BOND FUND INVESTOR ...,USA,NMFQS,USD,FUND,NaN
105,AALVX,THRIVENT PARTNER SMALL CAP VALUE FUND CLASS A,USA,NMFQS,USD,FUND,NaN
106,AAMAJX,AAMAJX,USA,NMFQS,USD,Mutual Fund,NaN
107,AAMEDX,AAMEDX,USA,NMFQS,USD,FUND,NaN
108,AAMENX,AAMENX,USA,NMFQS,USD,FUND,NaN
109,AAMEOX,AAMEOX,USA,NMFQS,USD,FUND,NaN
110,AAMKZX,AAMKZX,USA,NMFQS,USD,FUND,NaN
111,AAMLRX,AAMLRX,USA,NMFQS,USD,Mutual Fund,NaN
112,AAMLSX,AAMLSX,USA,NMFQS,USD,FUND,NaN
113,AAMLTX,AAMLTX,USA,NMFQS,USD,FUND,NaN
114,AAMLUX,AAMLUX,USA,NMFQS,USD,FUND,NaN
115,AAMLVX,AAMLVX,USA,NMFQS,USD,FUND,NaN
116,AAMLZX,AAMLZX,USA,NMFQS,USD,FUND,NaN
117,AAMPA,Apollo Global Management Inc Pfd,USA,NaN,USD,Common Stock,NaN
118,AAMPX,ALLIANZGI MICRO CAP FUND CLASS P,USA,NMFQS,USD,FUND,NaN
119,AAMPZX,AAMPZX,USA,NMFQS,USD,Mutual Fund,NaN
120,AAMQHX,AAMQHX,USA,NMFQS,USD,FUND,NaN
121,AAMQIX,AAMQIX,USA,NMFQS,USD,FUND,NaN
122,AAMQJX,AAMQJX,USA,NMFQS,USD,Mutual Fund,NaN
123,AAMRQ,American Airlines Group Inc.,USA,NYSE,USD,Common Stock,NaN
124,AAMRX,AMERICAN BEACON EMERGING MARKETS FUND AMR CLASS,USA,NMFQS,USD,FUND,NaN
125,AAMTCX,AAMTCX,USA,NMFQS,USD,Mutual Fund,NaN
126,AAMTIX,AAMTIX,USA,NMFQS,USD,FUND,NaN
127,AAMTMX,AAMTMX,USA,NMFQS,USD,Mutual Fund,NaN
128,AAMTNX,AAMTNX,USA,NMFQS,USD,Mutual Fund,NaN
129,AAMTVX,AAMTVX,USA,NMFQS,USD,Mutual Fund,NaN
130,AAMUBX,AAMUBX,USA,NMFQS,USD,Mutual Fund,NaN
131,AAMUKX,AAMUKX,USA,NMFQS,USD,Mutual Fund,NaN
132,AAMZAX,AAMZAX,USA,NMFQS,USD,Mutual Fund,NaN
133,AAN_old,AAN,USA,NYSE,USD,Common Stock,NaN
134,AAN-W,AAN-W,USA,NYSE,USD,Common Stock,NaN
135,AANB,Abigail Adams National Bancorp Inc,USA,NASDAQ,USD,Common Stock,NaN
136,AANC,AANC,USA,PINK,USD,Common Stock,NaN
137,AANOF,ASCIANO LTD,USA,PINK,USD,Common Stock,NaN
138,AANPX,AMERICAN BEACON RETIREMENT INCOME AND APPRECIA...,USA,NMFQS,USD,FUND,NaN
139,AANR,ANR Inc,USA,PINK,USD,Common Stock,NaN
140,AANXX,AANXX,USA,NMFQS,USD,Mutual Fund,NaN
141,AAOMF,Atlas Consolidated Mining and Development Corp...,USA,PINK,USD,Common Stock,PHY0434M1265
142,AAP1,Amway Asia Pacific Ltd,USA,NYSE,USD,Common Stock,NaN
143,AAPAX,AMERICAN BEACON RETIREMENT INCOME AND APPRECIA...,USA,NMFQS,USD,FUND,NaN
144,AAPC,Atlantic Alliance Partnership Corp,USA,NASDAQ,USD,Common Stock,NaN
145,AAPCF,Atlantic Alliance Partnership Corp - Ordinary ...,USA,PINK,USD,Common Stock,NaN
146,AAPEX,Aberdeen APAC ex-Japan Eq Ins Fd Inst Se,USA,NMFQS,USD,FUND,NaN
147,AAPH,American Petro-Hunter Inc,USA,OTCMKTS,USD,Common Stock,US0288571005
148,AAPIX,Aberdeen APAC ex-Japan Eq Insti Fd Inst,USA,NMFQS,USD,FUND,NaN
149,AAQC,Accelerate Acquisition Corp,USA,NYSE,USD,Common Stock,US00439D1028
150,AAQC-U,AAQC-U,USA,NYSE,USD,Common Stock,NaN
151,AAQC-UN,Accelerate Acquisition Units,USA,NASDAQ,USD,Common Stock,NaN
152,AAQC-WT,Accelerate Acquisition Corp.,USA,NYSE,USD,Common Stock,NaN
153,AAQCW,Accelerate Acquisition Corp.,USA,PINK,USD,Common Stock,NaN
154,AARAX,AB ALL MARKET ALTERNATIVE RETURN PORTFOLIO CLA...,USA,NMFQS,USD,FUND,NaN
155,AARBX,INVESCO REAL ESTATE FUND CLASS B,USA,NMFQS,USD,FUND,NaN
156,AARCX,AB ALL MARKET ALTERNATIVE RETURN PORTFOLIO CLA...,USA,NMFQS,USD,FUND,NaN
157,AARIX,ASTON/HARRISON STREET REAL ESTATE FUND CLASS I...,USA,NMFQS,USD,FUND,NaN
158,AARMX,AMERICAN INDEPENDENCE JAFORLINES GLOBAL TACTIC...,USA,NMFQS,USD,FUND,NaN
159,AARXF,AARXF,USA,PINK,USD,Common Stock,NaN
160,AARYX,AB ALL MARKET ALTERNATIVE RETURN PORTFOLIO ADV...,USA,NMFQS,USD,FUND,NaN
161,AASBX,AMERICAN BEACON SHORT-TERM BOND FUND INSTITUTI...,USA,NMFQS,USD,FUND,NaN
162,AASCF,All Active Asset Capital Limited,USA,OTCGREY,USD,Common Stock,NaN
163,AASL,America's Suppliers Inc,USA,PINK,USD,Common Stock,NaN
164,AASPX,AMERICAN BEACON S&P 500 INDEX FUND INSTITUTION...,USA,NMFQS,USD,FUND,NaN
165,AAST,Allied American Steel Corp,USA,OTCMKTS,USD,Common Stock,NaN
166,AASVX,AMERICAN BEACON SMALL CAP VALUE FUND AMR CLASS,USA,NMFQS,USD,FUND,NaN
167,AAT_old,All American Term Trust Inc,USA,NYSE,USD,Common Stock,NaN
168,AATAF,AATAF,USA,OTCGREY,USD,Common Stock,NaN
169,AATCX,ANCORA/THELEN SMALL-MID CAP CLASS C,USA,NMFQS,USD,FUND,NaN
170,AATDF,AA plc,USA,PINK,USD,Common Stock,NaN
171,AATFX,INTERMEDIATE TAX-FREE BOND FUND CLASS A,USA,NMFQS,USD,FUND,NaN
172,AATI,Advanced Analogic Technologies Incorp.,USA,NASDAQ,USD,Common Stock,NaN
173,AATI1,Analysis & Technology Inc,USA,NASDAQ,USD,Common Stock,NaN
174,AATP,Agape ATP Corporation,USA,PINK,USD,Common Stock,NaN
175,AATRX,AATRX,USA,NMFQS,USD,Mutual Fund,NaN
176,AATT,Aavid Thermal Technologies Inc,USA,NASDAQ,USD,Common Stock,NaN
177,AATYX,AATYX,USA,NMFQS,USD,Mutual Fund,NaN
178,AAUPX,ALLIANZGI ULTRA MICRO CAP FUND CLASS P,USA,NMFQS,USD,FUND,NaN
179,AAV,Advantage Oil & Gas Ltd,USA,NYSE,USD,Common Stock,US0036872093
180,AAV1,Avatex Corp,USA,NYSE,USD,Common Stock,NaN
181,AAVIX,ASTON/CORNERSTONE LARGE CAP VALUE FUND CLASS I...,USA,NMFQS,USD,FUND,NaN
182,AAVL,AAVL,USA,NASDAQ,USD,Common Stock,NaN
183,AAVPX,AMG MANAGERS VALUE PARTNERS ASIA DIVIDEND FUND...,USA,NMFQS,USD,FUND,NaN
184,AAVX,ETRACS Daily Short 1-Month S&P 500 VIX,USA,NYSE,USD,ETF,NaN
185,AAVXX,AAVXX,USA,NMFQS,USD,Mutual Fund,NaN
186,AAWC,Canning Str Corp,USA,PINK,USD,Common Stock,NaN
187,AAWCD,Canning Str Corp,USA,PINK,USD,Common Stock,NaN
188,AAWHQ,Atlas Air Worldwide Holdings Inc,USA,NASDAQ,USD,Common Stock,NaN
189,AAWW,Atlas Air Worldwide Holdings,USA,NASDAQ,USD,Common Stock,US0491642056
190,AAXAX,ADAPTIVE ALLOCATION FUND ADAPTIVE ALLOCATION F...,USA,NMFQS,USD,FUND,NaN
191,AAXCX,ADAPTIVE ALLOCATION FUND ADAPTIVE ALLOCATION F...,USA,NMFQS,USD,FUND,NaN
192,AAZBX,AB ARIZONA PORTFOLIO CLASS B,USA,NMFQS,USD,FUND,NaN
193,AAZYX,AB Municipal Income Fund II Arizona Portfolio ...,USA,NMFQS,USD,FUND,NaN
194,AAZYX_old,ALGER MID CAP FOCUS FUND ALGER MID CAP FOCUS F...,USA,NMFQS,USD,FUND,NaN
195,AAZZD,A2Z Smart Technologies Corp,USA,OTCQB,USD,Common Stock,NaN
196,AAZZF,A2Z Smart Technologies Corp,USA,OTCQX,USD,Common Stock,CA00249W1005
197,ABAAX,FORWARD BALANCED ALLOCATION FUND INSTITUTIONAL...,USA,NMFQS,USD,FUND,NaN
198,ABAC,Renmin Tianli Group Inc,USA,NASDAQ,USD,Common Stock,USG0404E1123
199,ABACF,Abacan Resource Corp,USA,NASDAQ,USD,Common Stock,NaN

In [67]:
sl[ sl['Name'].str.contains('pple')]

,Code,Name,Country,Exchange,Currency,Type,Isin
195,AAPL,Apple Inc,USA,NASDAQ,USD,Common Stock,US0378331005
1308,AGPL,Apple Green Holding Inc,USA,PINK,USD,Common Stock,NaN
2525,APLE,Apple Hospitality REIT Inc,USA,NYSE,USD,Common Stock,US03784Y2000
2585,APRU,Apple Rush Company,USA,PINK,USD,Common Stock,US03785R2040
18444,GAPJ,Golden Apple Oil & Gas Inc,USA,PINK,USD,Common Stock,NaN
19378,GJS,STRATSSM Certificates series supplement 2006-2...,USA,NYSE,USD,Common Stock,US86311R3012
30888,MLP,Maui Land & Pineapple Company Inc,USA,NYSE,USD,Common Stock,US5773451019
36383,PEGY,Pineapple Holdings Inc,USA,NASDAQ,USD,Common Stock,US72303P1075
37746,PNPL,Pineapple Express,USA,OTCCE,USD,Common Stock,US72302T1007

In [70]:
csv.dropna(subset='Name', inplace=True)
csv[ csv['Name'].str.contains('pple')]

,Code,Name,Country,Exchange,Currency,Type,Isin
1482,AGPL,Apple Green Holding Inc,USA,PINK,USD,Common Stock,NaN
2825,AOIA,Apple Orthodontix Inc,USA,NYSE,USD,Common Stock,NaN
3051,APWD,Applewoods Inc,USA,NASDAQ,USD,Common Stock,NaN
13710,DPS,Dr Pepper Snapple Group Inc,USA,NYSE,USD,Common Stock,US26138E1091
50965,TAVI,Thorn Apple Valley Inc,USA,NASDAQ,USD,Common Stock,NaN