In [46]:
import pandas as pd
%run Ratios.ipynb

oh dear
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2009-02-28   ADBE 2009-02-28  2009  2  0      0
AAPL   2009-03-31   AAPL 2009-03-31  2009  3  0      0
NVDA   2009-01-31   NVDA 2009-01-31  2009  1  0      0
BAM    2009-03-31    BAM 2009-03-31  2009  3  0      0
NEE    2009-03-31    NEE 2009-03-31  2009  3  0      0
...                  ...        ...   ... .. ..    ...
MTZ    2009-03-31    MTZ 2009-03-31  2009  3  0      0
NEON   2009-03-31   NEON 2009-03-31  2009  3  0      0
STCN   2009-01-31   STCN 2009-01-31  2009  1  0      0
VIAV   2009-03-31   VIAV 2009-03-31  2009  3  0      0
REFR   2009-03-31   REFR 2009-03-31  2009  3  0      0

[2389 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2009-05-31   ADBE 2009-05-31  2009  5  1      1
AAPL   2009-06-30   AAPL 2009-06-30  2009  6  1      1
NVDA   2009-04-30   NVDA 2009-04-30  2009  4  1      1
BAM    2009-06-30    BAM 2009-06-30  2009  6  1      1
NEE    2009-06-30    NEE 2009-06-30  2009  6  1      1
...                  ...        ...   ... .. ..    ...
MTZ    2009-06-30    MTZ 2009-06-30  2009  6  1      1
NEON   2009-06-30   NEON 2009-06-30  2009  6  1      1
STCN   2009-04-30   STCN 2009-04-30  2009  4  1      1
VIAV   2009-06-30   VIAV 2009-06-30  2009  6  1      1
REFR   2009-06-30   REFR 2009-06-30  2009  6  1      1

[2422 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2009-08-31   ADBE 2009-08-31  2009  8  2      2
AAPL   2009-09-30   AAPL 2009-09-30  2009  9  2      2
NVDA   2009-07-31   NVDA 2009-07-31  2009  7  2      2
BAM    2009-09-30    BAM 2009-09-30  2009  9  2      2
NEE    2009-09-30    NEE 2009-09-30  2009  9  2      2
...                  ...        ...   ... .. ..    ...
MTZ    2009-09-30    MTZ 2009-09-30  2009  9  2      2
NEON   2009-09-30   NEON 2009-09-30  2009  9  2      2
STCN   2009-07-31   STCN 2009-07-31  2009  7  2      2
VIAV   2009-09-30   VIAV 2009-09-30  2009  9  2      2
REFR   2009-09-30   REFR 2009-09-30  2009  9  2      2

[2420 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
ADBE   2009-11-30   ADBE 2009-11-30  2009  11  3      3
AAPL   2009-12-31   AAPL 2009-12-31  2009  12  3      3
NVDA   2009-10-31   NVDA 2009-10-31  2009  10  3      3
BAM    2009-12-31    BAM 2009-12-31  2009  12  3      3
NEE    2009-12-31    NEE 2009-12-31  2009  12  3      3
...                  ...        ...   ...  .. ..    ...
INPX   2009-12-31   INPX 2009-12-31  2009  12  3      3
NEON   2009-12-31   NEON 2009-12-31  2009  12  3      3
STCN   2009-10-31   STCN 2009-10-31  2009  10  3      3
VIAV   2009-12-31   VIAV 2009-12-31  2009  12  3      3
REFR   2009-12-31   REFR 2009-12-31  2009  12  3      3

[2506 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2010-02-28   ADBE 2010-02-28  2010  2  0      4
AAPL   2010-03-31   AAPL 2010-03-31  2010  3  0      4
NVDA   2010-01-31   NVDA 2010-01-31  2010  1  0      4
BAM    2010-03-31    BAM 2010-03-31  2010  3  0      4
NEE    2010-03-31    NEE 2010-03-31  2010  3  0      4
...                  ...        ...   ... .. ..    ...
MTZ    2010-03-31    MTZ 2010-03-31  2010  3  0      4
NEON   2010-03-31   NEON 2010-03-31  2010  3  0      4
STCN   2010-01-31   STCN 2010-01-31  2010  1  0      4
VIAV   2010-03-31   VIAV 2010-03-31  2010  3  0      4
REFR   2010-03-31   REFR 2010-03-31  2010  3  0      4

[2464 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2010-05-31   ADBE 2010-05-31  2010  5  1      5
AAPL   2010-06-30   AAPL 2010-06-30  2010  6  1      5
NVDA   2010-04-30   NVDA 2010-04-30  2010  4  1      5
BAM    2010-06-30    BAM 2010-06-30  2010  6  1      5
NEE    2010-06-30    NEE 2010-06-30  2010  6  1      5
...                  ...        ...   ... .. ..    ...
MTZ    2010-06-30    MTZ 2010-06-30  2010  6  1      5
NEON   2010-06-30   NEON 2010-06-30  2010  6  1      5
STCN   2010-04-30   STCN 2010-04-30  2010  4  1      5
VIAV   2010-06-30   VIAV 2010-06-30  2010  6  1      5
REFR   2010-06-30   REFR 2010-06-30  2010  6  1      5

[2500 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2010-08-31   ADBE 2010-08-31  2010  8  2      6
AAPL   2010-09-30   AAPL 2010-09-30  2010  9  2      6
NVDA   2010-07-31   NVDA 2010-07-31  2010  7  2      6
BAM    2010-09-30    BAM 2010-09-30  2010  9  2      6
NEE    2010-09-30    NEE 2010-09-30  2010  9  2      6
...                  ...        ...   ... .. ..    ...
MTZ    2010-09-30    MTZ 2010-09-30  2010  9  2      6
NEON   2010-09-30   NEON 2010-09-30  2010  9  2      6
STCN   2010-07-31   STCN 2010-07-31  2010  7  2      6
VIAV   2010-09-30   VIAV 2010-09-30  2010  9  2      6
REFR   2010-09-30   REFR 2010-09-30  2010  9  2      6

[2490 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
ADBE   2010-11-30   ADBE 2010-11-30  2010  11  3      7
AAPL   2010-12-31   AAPL 2010-12-31  2010  12  3      7
NVDA   2010-10-31   NVDA 2010-10-31  2010  10  3      7
FBIO   2010-12-31   FBIO 2010-12-31  2010  12  3      7
BAM    2010-12-31    BAM 2010-12-31  2010  12  3      7
...                  ...        ...   ...  .. ..    ...
ALYA   2010-12-31   ALYA 2010-12-31  2010  12  3      7
NEON   2010-12-31   NEON 2010-12-31  2010  12  3      7
STCN   2010-10-31   STCN 2010-10-31  2010  10  3      7
VIAV   2010-12-31   VIAV 2010-12-31  2010  12  3      7
REFR   2010-12-31   REFR 2010-12-31  2010  12  3      7

[2602 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2011-02-28   ADBE 2011-02-28  2011  2  0      8
AAPL   2011-03-31   AAPL 2011-03-31  2011  3  0      8
NVDA   2011-01-31   NVDA 2011-01-31  2011  1  0      8
BAM    2011-03-31    BAM 2011-03-31  2011  3  0      8
NEE    2011-03-31    NEE 2011-03-31  2011  3  0      8
...                  ...        ...   ... .. ..    ...
MTZ    2011-03-31    MTZ 2011-03-31  2011  3  0      8
NEON   2011-03-31   NEON 2011-03-31  2011  3  0      8
STCN   2011-01-31   STCN 2011-01-31  2011  1  0      8
VIAV   2011-03-31   VIAV 2011-03-31  2011  3  0      8
REFR   2011-03-31   REFR 2011-03-31  2011  3  0      8

[2578 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2011-05-31   ADBE 2011-05-31  2011  5  1      9
AAPL   2011-06-30   AAPL 2011-06-30  2011  6  1      9
NVDA   2011-04-30   NVDA 2011-04-30  2011  4  1      9
AMCX   2011-06-30   AMCX 2011-06-30  2011  6  1      9
BAM    2011-06-30    BAM 2011-06-30  2011  6  1      9
...                  ...        ...   ... .. ..    ...
MTZ    2011-06-30    MTZ 2011-06-30  2011  6  1      9
NEON   2011-06-30   NEON 2011-06-30  2011  6  1      9
STCN   2011-04-30   STCN 2011-04-30  2011  4  1      9
VIAV   2011-06-30   VIAV 2011-06-30  2011  6  1      9
REFR   2011-06-30   REFR 2011-06-30  2011  6  1      9

[2619 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2011-08-31   ADBE 2011-08-31  2011  8  2     10
AAPL   2011-09-30   AAPL 2011-09-30  2011  9  2     10
NVDA   2011-07-31   NVDA 2011-07-31  2011  7  2     10
AMCX   2011-09-30   AMCX 2011-09-30  2011  9  2     10
FBIO   2011-09-30   FBIO 2011-09-30  2011  9  2     10
...                  ...        ...   ... .. ..    ...
MTZ    2011-09-30    MTZ 2011-09-30  2011  9  2     10
NEON   2011-09-30   NEON 2011-09-30  2011  9  2     10
STCN   2011-07-31   STCN 2011-07-31  2011  7  2     10
VIAV   2011-09-30   VIAV 2011-09-30  2011  9  2     10
REFR   2011-09-30   REFR 2011-09-30  2011  9  2     10

[2613 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
ADBE   2011-11-30   ADBE 2011-11-30  2011  11  3     11
AAPL   2011-12-31   AAPL 2011-12-31  2011  12  3     11
NVDA   2011-10-31   NVDA 2011-10-31  2011  10  3     11
AMCX   2011-12-31   AMCX 2011-12-31  2011  12  3     11
FBIO   2011-12-31   FBIO 2011-12-31  2011  12  3     11
...                  ...        ...   ...  .. ..    ...
INPX   2011-12-31   INPX 2011-12-31  2011  12  3     11
NEON   2011-12-31   NEON 2011-12-31  2011  12  3     11
STCN   2011-10-31   STCN 2011-10-31  2011  10  3     11
VIAV   2011-12-31   VIAV 2011-12-31  2011  12  3     11
REFR   2011-12-31   REFR 2011-12-31  2011  12  3     11

[2778 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2012-02-29   ADBE 2012-02-29  2012  2  0     12
AAPL   2012-03-31   AAPL 2012-03-31  2012  3  0     12
NVDA   2012-01-31   NVDA 2012-01-31  2012  1  0     12
AMCX   2012-03-31   AMCX 2012-03-31  2012  3  0     12
FBIO   2012-03-31   FBIO 2012-03-31  2012  3  0     12
...                  ...        ...   ... .. ..    ...
MTZ    2012-03-31    MTZ 2012-03-31  2012  3  0     12
NEON   2012-03-31   NEON 2012-03-31  2012  3  0     12
STCN   2012-01-31   STCN 2012-01-31  2012  1  0     12
VIAV   2012-03-31   VIAV 2012-03-31  2012  3  0     12
REFR   2012-03-31   REFR 2012-03-31  2012  3  0     12

[2673 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2012-05-31   ADBE 2012-05-31  2012  5  1     13
AAPL   2012-06-30   AAPL 2012-06-30  2012  6  1     13
NVDA   2012-04-30   NVDA 2012-04-30  2012  4  1     13
AMCX   2012-06-30   AMCX 2012-06-30  2012  6  1     13
FBIO   2012-06-30   FBIO 2012-06-30  2012  6  1     13
...                  ...        ...   ... .. ..    ...
MTZ    2012-06-30    MTZ 2012-06-30  2012  6  1     13
NEON   2012-06-30   NEON 2012-06-30  2012  6  1     13
STCN   2012-04-30   STCN 2012-04-30  2012  4  1     13
VIAV   2012-06-30   VIAV 2012-06-30  2012  6  1     13
REFR   2012-06-30   REFR 2012-06-30  2012  6  1     13

[2708 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2012-08-31   ADBE 2012-08-31  2012  8  2     14
AAPL   2012-09-30   AAPL 2012-09-30  2012  9  2     14
NVDA   2012-07-31   NVDA 2012-07-31  2012  7  2     14
AMCX   2012-09-30   AMCX 2012-09-30  2012  9  2     14
FBIO   2012-09-30   FBIO 2012-09-30  2012  9  2     14
...                  ...        ...   ... .. ..    ...
MTZ    2012-09-30    MTZ 2012-09-30  2012  9  2     14
NEON   2012-09-30   NEON 2012-09-30  2012  9  2     14
STCN   2012-07-31   STCN 2012-07-31  2012  7  2     14
VIAV   2012-09-30   VIAV 2012-09-30  2012  9  2     14
REFR   2012-09-30   REFR 2012-09-30  2012  9  2     14

[2711 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2012-12-31   SABR 2012-12-31  2012  12  3     15
ADBE   2012-11-30   ADBE 2012-11-30  2012  11  3     15
AAPL   2012-12-31   AAPL 2012-12-31  2012  12  3     15
NVDA   2012-10-31   NVDA 2012-10-31  2012  10  3     15
AMCX   2012-12-31   AMCX 2012-12-31  2012  12  3     15
...                  ...        ...   ...  .. ..    ...
LKCO   2012-12-31   LKCO 2012-12-31  2012  12  3     15
NEON   2012-12-31   NEON 2012-12-31  2012  12  3     15
STCN   2012-10-31   STCN 2012-10-31  2012  10  3     15
VIAV   2012-12-31   VIAV 2012-12-31  2012  12  3     15
REFR   2012-12-31   REFR 2012-12-31  2012  12  3     15

[2937 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2013-02-28   ADBE 2013-02-28  2013  2  0     16
AAPL   2013-03-31   AAPL 2013-03-31  2013  3  0     16
NVDA   2013-01-31   NVDA 2013-01-31  2013  1  0     16
AMCX   2013-03-31   AMCX 2013-03-31  2013  3  0     16
FBIO   2013-03-31   FBIO 2013-03-31  2013  3  0     16
...                  ...        ...   ... .. ..    ...
MTZ    2013-03-31    MTZ 2013-03-31  2013  3  0     16
NEON   2013-03-31   NEON 2013-03-31  2013  3  0     16
STCN   2013-01-31   STCN 2013-01-31  2013  1  0     16
VIAV   2013-03-31   VIAV 2013-03-31  2013  3  0     16
REFR   2013-03-31   REFR 2013-03-31  2013  3  0     16

[2794 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2013-05-31   ADBE 2013-05-31  2013  5  1     17
AAPL   2013-06-30   AAPL 2013-06-30  2013  6  1     17
NVDA   2013-04-30   NVDA 2013-04-30  2013  4  1     17
AMCX   2013-06-30   AMCX 2013-06-30  2013  6  1     17
FBIO   2013-06-30   FBIO 2013-06-30  2013  6  1     17
...                  ...        ...   ... .. ..    ...
MTZ    2013-06-30    MTZ 2013-06-30  2013  6  1     17
NEON   2013-06-30   NEON 2013-06-30  2013  6  1     17
STCN   2013-04-30   STCN 2013-04-30  2013  4  1     17
VIAV   2013-06-30   VIAV 2013-06-30  2013  6  1     17
REFR   2013-06-30   REFR 2013-06-30  2013  6  1     17

[2846 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2013-08-31   ADBE 2013-08-31  2013  8  2     18
AAPL   2013-09-30   AAPL 2013-09-30  2013  9  2     18
NVDA   2013-07-31   NVDA 2013-07-31  2013  7  2     18
AMCX   2013-09-30   AMCX 2013-09-30  2013  9  2     18
FBIO   2013-09-30   FBIO 2013-09-30  2013  9  2     18
...                  ...        ...   ... .. ..    ...
MTZ    2013-09-30    MTZ 2013-09-30  2013  9  2     18
NEON   2013-09-30   NEON 2013-09-30  2013  9  2     18
STCN   2013-07-31   STCN 2013-07-31  2013  7  2     18
VIAV   2013-09-30   VIAV 2013-09-30  2013  9  2     18
REFR   2013-09-30   REFR 2013-09-30  2013  9  2     18

[2857 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2013-12-31   SABR 2013-12-31  2013  12  3     19
ADBE   2013-11-30   ADBE 2013-11-30  2013  11  3     19
AAPL   2013-12-31   AAPL 2013-12-31  2013  12  3     19
NVDA   2013-10-31   NVDA 2013-10-31  2013  10  3     19
AMCX   2013-12-31   AMCX 2013-12-31  2013  12  3     19
...                  ...        ...   ...  .. ..    ...
LKCO   2013-12-31   LKCO 2013-12-31  2013  12  3     19
NEON   2013-12-31   NEON 2013-12-31  2013  12  3     19
STCN   2013-10-31   STCN 2013-10-31  2013  10  3     19
VIAV   2013-12-31   VIAV 2013-12-31  2013  12  3     19
REFR   2013-12-31   REFR 2013-12-31  2013  12  3     19

[3065 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2014-03-31   SABR 2014-03-31  2014  3  0     20
ADBE   2014-02-28   ADBE 2014-02-28  2014  2  0     20
AAPL   2014-03-31   AAPL 2014-03-31  2014  3  0     20
NVDA   2014-01-31   NVDA 2014-01-31  2014  1  0     20
AMCX   2014-03-31   AMCX 2014-03-31  2014  3  0     20
...                  ...        ...   ... .. ..    ...
MTZ    2014-03-31    MTZ 2014-03-31  2014  3  0     20
NEON   2014-03-31   NEON 2014-03-31  2014  3  0     20
STCN   2014-01-31   STCN 2014-01-31  2014  1  0     20
VIAV   2014-03-31   VIAV 2014-03-31  2014  3  0     20
REFR   2014-03-31   REFR 2014-03-31  2014  3  0     20

[2993 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2014-06-30   SABR 2014-06-30  2014  6  1     21
ADBE   2014-05-31   ADBE 2014-05-31  2014  5  1     21
AAPL   2014-06-30   AAPL 2014-06-30  2014  6  1     21
NVDA   2014-04-30   NVDA 2014-04-30  2014  4  1     21
AMCX   2014-06-30   AMCX 2014-06-30  2014  6  1     21
...                  ...        ...   ... .. ..    ...
MTZ    2014-06-30    MTZ 2014-06-30  2014  6  1     21
NEON   2014-06-30   NEON 2014-06-30  2014  6  1     21
STCN   2014-04-30   STCN 2014-04-30  2014  4  1     21
VIAV   2014-06-30   VIAV 2014-06-30  2014  6  1     21
REFR   2014-06-30   REFR 2014-06-30  2014  6  1     21

[3066 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2014-09-30   SABR 2014-09-30  2014  9  2     22
ADBE   2014-08-31   ADBE 2014-08-31  2014  8  2     22
AAPL   2014-09-30   AAPL 2014-09-30  2014  9  2     22
NVDA   2014-07-31   NVDA 2014-07-31  2014  7  2     22
AMCX   2014-09-30   AMCX 2014-09-30  2014  9  2     22
...                  ...        ...   ... .. ..    ...
MTZ    2014-09-30    MTZ 2014-09-30  2014  9  2     22
NEON   2014-09-30   NEON 2014-09-30  2014  9  2     22
STCN   2014-07-31   STCN 2014-07-31  2014  7  2     22
VIAV   2014-09-30   VIAV 2014-09-30  2014  9  2     22
REFR   2014-09-30   REFR 2014-09-30  2014  9  2     22

[3078 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2014-12-31   SABR 2014-12-31  2014  12  3     23
ADBE   2014-11-30   ADBE 2014-11-30  2014  11  3     23
AAPL   2014-12-31   AAPL 2014-12-31  2014  12  3     23
NVDA   2014-10-31   NVDA 2014-10-31  2014  10  3     23
AMCX   2014-12-31   AMCX 2014-12-31  2014  12  3     23
...                  ...        ...   ...  .. ..    ...
LKCO   2014-12-31   LKCO 2014-12-31  2014  12  3     23
NEON   2014-12-31   NEON 2014-12-31  2014  12  3     23
STCN   2014-10-31   STCN 2014-10-31  2014  10  3     23
VIAV   2014-12-31   VIAV 2014-12-31  2014  12  3     23
REFR   2014-12-31   REFR 2014-12-31  2014  12  3     23

[3262 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2015-03-31   SABR 2015-03-31  2015  3  0     24
ADBE   2015-02-28   ADBE 2015-02-28  2015  2  0     24
AAPL   2015-03-31   AAPL 2015-03-31  2015  3  0     24
NVDA   2015-01-31   NVDA 2015-01-31  2015  1  0     24
AMCX   2015-03-31   AMCX 2015-03-31  2015  3  0     24
...                  ...        ...   ... .. ..    ...
MTZ    2015-03-31    MTZ 2015-03-31  2015  3  0     24
NEON   2015-03-31   NEON 2015-03-31  2015  3  0     24
STCN   2015-01-31   STCN 2015-01-31  2015  1  0     24
VIAV   2015-03-31   VIAV 2015-03-31  2015  3  0     24
REFR   2015-03-31   REFR 2015-03-31  2015  3  0     24

[3164 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2015-06-30   SABR 2015-06-30  2015  6  1     25
ADBE   2015-05-31   ADBE 2015-05-31  2015  5  1     25
AAPL   2015-06-30   AAPL 2015-06-30  2015  6  1     25
NVDA   2015-04-30   NVDA 2015-04-30  2015  4  1     25
AMCX   2015-06-30   AMCX 2015-06-30  2015  6  1     25
...                  ...        ...   ... .. ..    ...
MTZ    2015-06-30    MTZ 2015-06-30  2015  6  1     25
NEON   2015-06-30   NEON 2015-06-30  2015  6  1     25
STCN   2015-04-30   STCN 2015-04-30  2015  4  1     25
VIAV   2015-06-30   VIAV 2015-06-30  2015  6  1     25
REFR   2015-06-30   REFR 2015-06-30  2015  6  1     25

[3237 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2015-09-30   SABR 2015-09-30  2015  9  2     26
ADBE   2015-08-31   ADBE 2015-08-31  2015  8  2     26
AAPL   2015-09-30   AAPL 2015-09-30  2015  9  2     26
NVDA   2015-07-31   NVDA 2015-07-31  2015  7  2     26
AMCX   2015-09-30   AMCX 2015-09-30  2015  9  2     26
...                  ...        ...   ... .. ..    ...
NEON   2015-09-30   NEON 2015-09-30  2015  9  2     26
STCN   2015-07-31   STCN 2015-07-31  2015  7  2     26
VIAV   2015-09-30   VIAV 2015-09-30  2015  9  2     26
REFR   2015-09-30   REFR 2015-09-30  2015  9  2     26
LILAK  2015-09-30  LILAK 2015-09-30  2015  9  2     26

[3226 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2015-12-31   SABR 2015-12-31  2015  12  3     27
ADBE   2015-11-30   ADBE 2015-11-30  2015  11  3     27
ACMR   2015-12-31   ACMR 2015-12-31  2015  12  3     27
AAPL   2015-12-31   AAPL 2015-12-31  2015  12  3     27
NVDA   2015-10-31   NVDA 2015-10-31  2015  10  3     27
...                  ...        ...   ...  .. ..    ...
NEON   2015-12-31   NEON 2015-12-31  2015  12  3     27
STCN   2015-10-31   STCN 2015-10-31  2015  10  3     27
VIAV   2015-12-31   VIAV 2015-12-31  2015  12  3     27
REFR   2015-12-31   REFR 2015-12-31  2015  12  3     27
LILAK  2015-12-31  LILAK 2015-12-31  2015  12  3     27

[3418 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2016-03-31   SABR 2016-03-31  2016  3  0     28
ADBE   2016-02-29   ADBE 2016-02-29  2016  2  0     28
AAPL   2016-03-31   AAPL 2016-03-31  2016  3  0     28
NVDA   2016-01-31   NVDA 2016-01-31  2016  1  0     28
AMCX   2016-03-31   AMCX 2016-03-31  2016  3  0     28
...                  ...        ...   ... .. ..    ...
NEON   2016-03-31   NEON 2016-03-31  2016  3  0     28
STCN   2016-01-31   STCN 2016-01-31  2016  1  0     28
VIAV   2016-03-31   VIAV 2016-03-31  2016  3  0     28
REFR   2016-03-31   REFR 2016-03-31  2016  3  0     28
LILAK  2016-03-31  LILAK 2016-03-31  2016  3  0     28

[3287 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2016-06-30   SABR 2016-06-30  2016  6  1     29
ADBE   2016-05-31   ADBE 2016-05-31  2016  5  1     29
AAPL   2016-06-30   AAPL 2016-06-30  2016  6  1     29
NVDA   2016-04-30   NVDA 2016-04-30  2016  4  1     29
AMCX   2016-06-30   AMCX 2016-06-30  2016  6  1     29
...                  ...        ...   ... .. ..    ...
STCN   2016-04-30   STCN 2016-04-30  2016  4  1     29
VIAV   2016-06-30   VIAV 2016-06-30  2016  6  1     29
REFR   2016-06-30   REFR 2016-06-30  2016  6  1     29
LSXMB  2016-06-30  LSXMB 2016-06-30  2016  6  1     29
LILAK  2016-06-30  LILAK 2016-06-30  2016  6  1     29

[3304 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2016-09-30   SABR 2016-09-30  2016  9  2     30
ADBE   2016-08-31   ADBE 2016-08-31  2016  8  2     30
AAPL   2016-09-30   AAPL 2016-09-30  2016  9  2     30
NVDA   2016-07-31   NVDA 2016-07-31  2016  7  2     30
AMCX   2016-09-30   AMCX 2016-09-30  2016  9  2     30
...                  ...        ...   ... .. ..    ...
STCN   2016-07-31   STCN 2016-07-31  2016  7  2     30
VIAV   2016-09-30   VIAV 2016-09-30  2016  9  2     30
REFR   2016-09-30   REFR 2016-09-30  2016  9  2     30
LSXMB  2016-09-30  LSXMB 2016-09-30  2016  9  2     30
LILAK  2016-09-30  LILAK 2016-09-30  2016  9  2     30

[3334 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2016-12-31   SABR 2016-12-31  2016  12  3     31
ADBE   2016-11-30   ADBE 2016-11-30  2016  11  3     31
AAPL   2016-12-31   AAPL 2016-12-31  2016  12  3     31
NVDA   2016-10-31   NVDA 2016-10-31  2016  10  3     31
AMCX   2016-12-31   AMCX 2016-12-31  2016  12  3     31
...                  ...        ...   ...  .. ..    ...
VIAV   2016-12-31   VIAV 2016-12-31  2016  12  3     31
WISA   2016-12-31   WISA 2016-12-31  2016  12  3     31
REFR   2016-12-31   REFR 2016-12-31  2016  12  3     31
LSXMB  2016-12-31  LSXMB 2016-12-31  2016  12  3     31
LILAK  2016-12-31  LILAK 2016-12-31  2016  12  3     31

[3530 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2017-03-31   SABR 2017-03-31  2017  3  0     32
ADBE   2017-02-28   ADBE 2017-02-28  2017  2  0     32
AAPL   2017-03-31   AAPL 2017-03-31  2017  3  0     32
NVDA   2017-01-31   NVDA 2017-01-31  2017  1  0     32
AMCX   2017-03-31   AMCX 2017-03-31  2017  3  0     32
...                  ...        ...   ... .. ..    ...
STCN   2017-01-31   STCN 2017-01-31  2017  1  0     32
VIAV   2017-03-31   VIAV 2017-03-31  2017  3  0     32
REFR   2017-03-31   REFR 2017-03-31  2017  3  0     32
LSXMB  2017-03-31  LSXMB 2017-03-31  2017  3  0     32
LILAK  2017-03-31  LILAK 2017-03-31  2017  3  0     32

[3410 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2017-06-30   SABR 2017-06-30  2017  6  1     33
ADBE   2017-05-31   ADBE 2017-05-31  2017  5  1     33
AAPL   2017-06-30   AAPL 2017-06-30  2017  6  1     33
NVDA   2017-04-30   NVDA 2017-04-30  2017  4  1     33
AMCX   2017-06-30   AMCX 2017-06-30  2017  6  1     33
...                  ...        ...   ... .. ..    ...
VIAV   2017-06-30   VIAV 2017-06-30  2017  6  1     33
WISA   2017-06-30   WISA 2017-06-30  2017  6  1     33
REFR   2017-06-30   REFR 2017-06-30  2017  6  1     33
LSXMB  2017-06-30  LSXMB 2017-06-30  2017  6  1     33
LILAK  2017-06-30  LILAK 2017-06-30  2017  6  1     33

[3494 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2017-09-30   SABR 2017-09-30  2017  9  2     34
ADBE   2017-08-31   ADBE 2017-08-31  2017  8  2     34
ACMR   2017-09-30   ACMR 2017-09-30  2017  9  2     34
AAPL   2017-09-30   AAPL 2017-09-30  2017  9  2     34
NVDA   2017-07-31   NVDA 2017-07-31  2017  7  2     34
...                  ...        ...   ... .. ..    ...
VIAV   2017-09-30   VIAV 2017-09-30  2017  9  2     34
WISA   2017-09-30   WISA 2017-09-30  2017  9  2     34
REFR   2017-09-30   REFR 2017-09-30  2017  9  2     34
LSXMB  2017-09-30  LSXMB 2017-09-30  2017  9  2     34
LILAK  2017-09-30  LILAK 2017-09-30  2017  9  2     34

[3514 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2017-12-31   SABR 2017-12-31  2017  12  3     35
ADBE   2017-11-30   ADBE 2017-11-30  2017  11  3     35
ACMR   2017-12-31   ACMR 2017-12-31  2017  12  3     35
AAPL   2017-12-31   AAPL 2017-12-31  2017  12  3     35
NVDA   2017-10-31   NVDA 2017-10-31  2017  10  3     35
...                  ...        ...   ...  .. ..    ...
STCN   2017-10-31   STCN 2017-10-31  2017  10  3     35
VIAV   2017-12-31   VIAV 2017-12-31  2017  12  3     35
WISA   2017-12-31   WISA 2017-12-31  2017  12  3     35
REFR   2017-12-31   REFR 2017-12-31  2017  12  3     35
LSXMB  2017-12-31  LSXMB 2017-12-31  2017  12  3     35

[3674 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2018-03-31   SABR 2018-03-31  2018  3  0     36
ADBE   2018-02-28   ADBE 2018-02-28  2018  2  0     36
ACMR   2018-03-31   ACMR 2018-03-31  2018  3  0     36
AAPL   2018-03-31   AAPL 2018-03-31  2018  3  0     36
NVDA   2018-01-31   NVDA 2018-01-31  2018  1  0     36
...                  ...        ...   ... .. ..    ...
VIAV   2018-03-31   VIAV 2018-03-31  2018  3  0     36
WISA   2018-03-31   WISA 2018-03-31  2018  3  0     36
REFR   2018-03-31   REFR 2018-03-31  2018  3  0     36
LSXMB  2018-03-31  LSXMB 2018-03-31  2018  3  0     36
LILAK  2018-03-31  LILAK 2018-03-31  2018  3  0     36

[3624 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2018-06-30   SABR 2018-06-30  2018  6  1     37
ADBE   2018-05-31   ADBE 2018-05-31  2018  5  1     37
ACMR   2018-06-30   ACMR 2018-06-30  2018  6  1     37
AAPL   2018-06-30   AAPL 2018-06-30  2018  6  1     37
NVDA   2018-04-30   NVDA 2018-04-30  2018  4  1     37
...                  ...        ...   ... .. ..    ...
VIAV   2018-06-30   VIAV 2018-06-30  2018  6  1     37
WISA   2018-06-30   WISA 2018-06-30  2018  6  1     37
REFR   2018-06-30   REFR 2018-06-30  2018  6  1     37
LSXMB  2018-06-30  LSXMB 2018-06-30  2018  6  1     37
LILAK  2018-06-30  LILAK 2018-06-30  2018  6  1     37

[3701 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2018-09-30   SABR 2018-09-30  2018  9  2     38
ADBE   2018-08-31   ADBE 2018-08-31  2018  8  2     38
ACMR   2018-09-30   ACMR 2018-09-30  2018  9  2     38
AAPL   2018-09-30   AAPL 2018-09-30  2018  9  2     38
NVDA   2018-07-31   NVDA 2018-07-31  2018  7  2     38
...                  ...        ...   ... .. ..    ...
VIAV   2018-09-30   VIAV 2018-09-30  2018  9  2     38
WISA   2018-09-30   WISA 2018-09-30  2018  9  2     38
REFR   2018-09-30   REFR 2018-09-30  2018  9  2     38
LSXMB  2018-09-30  LSXMB 2018-09-30  2018  9  2     38
LILAK  2018-09-30  LILAK 2018-09-30  2018  9  2     38

[3712 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2018-12-31   SABR 2018-12-31  2018  12  3     39
ADBE   2018-11-30   ADBE 2018-11-30  2018  11  3     39
ACMR   2018-12-31   ACMR 2018-12-31  2018  12  3     39
AAPL   2018-12-31   AAPL 2018-12-31  2018  12  3     39
NVDA   2018-10-31   NVDA 2018-10-31  2018  10  3     39
...                  ...        ...   ...  .. ..    ...
VIAV   2018-12-31   VIAV 2018-12-31  2018  12  3     39
WISA   2018-12-31   WISA 2018-12-31  2018  12  3     39
REFR   2018-12-31   REFR 2018-12-31  2018  12  3     39
LSXMB  2018-12-31  LSXMB 2018-12-31  2018  12  3     39
LILAK  2018-12-31  LILAK 2018-12-31  2018  12  3     39

[3913 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2019-03-31   SABR 2019-03-31  2019  3  0     40
ADBE   2019-02-28   ADBE 2019-02-28  2019  2  0     40
ACMR   2019-03-31   ACMR 2019-03-31  2019  3  0     40
AAPL   2019-03-31   AAPL 2019-03-31  2019  3  0     40
NVDA   2019-01-31   NVDA 2019-01-31  2019  1  0     40
...                  ...        ...   ... .. ..    ...
VIAV   2019-03-31   VIAV 2019-03-31  2019  3  0     40
WISA   2019-03-31   WISA 2019-03-31  2019  3  0     40
REFR   2019-03-31   REFR 2019-03-31  2019  3  0     40
LSXMB  2019-03-31  LSXMB 2019-03-31  2019  3  0     40
LILAK  2019-03-31  LILAK 2019-03-31  2019  3  0     40

[3842 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2019-06-30   SABR 2019-06-30  2019  6  1     41
ADBE   2019-05-31   ADBE 2019-05-31  2019  5  1     41
ACMR   2019-06-30   ACMR 2019-06-30  2019  6  1     41
AAPL   2019-06-30   AAPL 2019-06-30  2019  6  1     41
NVDA   2019-04-30   NVDA 2019-04-30  2019  4  1     41
...                  ...        ...   ... .. ..    ...
VIAV   2019-06-30   VIAV 2019-06-30  2019  6  1     41
WISA   2019-06-30   WISA 2019-06-30  2019  6  1     41
REFR   2019-06-30   REFR 2019-06-30  2019  6  1     41
LSXMB  2019-06-30  LSXMB 2019-06-30  2019  6  1     41
LILAK  2019-06-30  LILAK 2019-06-30  2019  6  1     41

[3925 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2019-09-30   SABR 2019-09-30  2019  9  2     42
ADBE   2019-08-31   ADBE 2019-08-31  2019  8  2     42
ACMR   2019-09-30   ACMR 2019-09-30  2019  9  2     42
AAPL   2019-09-30   AAPL 2019-09-30  2019  9  2     42
NVDA   2019-07-31   NVDA 2019-07-31  2019  7  2     42
...                  ...        ...   ... .. ..    ...
VIAV   2019-09-30   VIAV 2019-09-30  2019  9  2     42
WISA   2019-09-30   WISA 2019-09-30  2019  9  2     42
REFR   2019-09-30   REFR 2019-09-30  2019  9  2     42
LSXMB  2019-09-30  LSXMB 2019-09-30  2019  9  2     42
LILAK  2019-09-30  LILAK 2019-09-30  2019  9  2     42

[3919 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2019-12-31   SABR 2019-12-31  2019  12  3     43
ADBE   2019-11-30   ADBE 2019-11-30  2019  11  3     43
ACMR   2019-12-31   ACMR 2019-12-31  2019  12  3     43
AAPL   2019-12-31   AAPL 2019-12-31  2019  12  3     43
NVDA   2019-10-31   NVDA 2019-10-31  2019  10  3     43
...                  ...        ...   ...  .. ..    ...
VIAV   2019-12-31   VIAV 2019-12-31  2019  12  3     43
WISA   2019-12-31   WISA 2019-12-31  2019  12  3     43
REFR   2019-12-31   REFR 2019-12-31  2019  12  3     43
LSXMB  2019-12-31  LSXMB 2019-12-31  2019  12  3     43
LILAK  2019-12-31  LILAK 2019-12-31  2019  12  3     43

[4272 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2020-03-31   SABR 2020-03-31  2020  3  0     44
ADBE   2020-02-29   ADBE 2020-02-29  2020  2  0     44
ACMR   2020-03-31   ACMR 2020-03-31  2020  3  0     44
AAPL   2020-03-31   AAPL 2020-03-31  2020  3  0     44
NVDA   2020-01-31   NVDA 2020-01-31  2020  1  0     44
...                  ...        ...   ... .. ..    ...
VIAV   2020-03-31   VIAV 2020-03-31  2020  3  0     44
WISA   2020-03-31   WISA 2020-03-31  2020  3  0     44
REFR   2020-03-31   REFR 2020-03-31  2020  3  0     44
LSXMB  2020-03-31  LSXMB 2020-03-31  2020  3  0     44
LILAK  2020-03-31  LILAK 2020-03-31  2020  3  0     44

[4018 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2020-06-30   SABR 2020-06-30  2020  6  1     45
ADBE   2020-05-31   ADBE 2020-05-31  2020  5  1     45
ACMR   2020-06-30   ACMR 2020-06-30  2020  6  1     45
AAPL   2020-06-30   AAPL 2020-06-30  2020  6  1     45
NVDA   2020-04-30   NVDA 2020-04-30  2020  4  1     45
...                  ...        ...   ... .. ..    ...
VIAV   2020-06-30   VIAV 2020-06-30  2020  6  1     45
WISA   2020-06-30   WISA 2020-06-30  2020  6  1     45
REFR   2020-06-30   REFR 2020-06-30  2020  6  1     45
LSXMB  2020-06-30  LSXMB 2020-06-30  2020  6  1     45
LILAK  2020-06-30  LILAK 2020-06-30  2020  6  1     45

[4147 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2020-09-30   SABR 2020-09-30  2020  9  2     46
ADBE   2020-08-31   ADBE 2020-08-31  2020  8  2     46
ACMR   2020-09-30   ACMR 2020-09-30  2020  9  2     46
AAPL   2020-09-30   AAPL 2020-09-30  2020  9  2     46
NVDA   2020-07-31   NVDA 2020-07-31  2020  7  2     46
...                  ...        ...   ... .. ..    ...
VIAV   2020-09-30   VIAV 2020-09-30  2020  9  2     46
WISA   2020-09-30   WISA 2020-09-30  2020  9  2     46
REFR   2020-09-30   REFR 2020-09-30  2020  9  2     46
LSXMB  2020-09-30  LSXMB 2020-09-30  2020  9  2     46
LILAK  2020-09-30  LILAK 2020-09-30  2020  9  2     46

[4293 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2020-12-31   SABR 2020-12-31  2020  12  3     47
ADBE   2020-11-30   ADBE 2020-11-30  2020  11  3     47
ACMR   2020-12-31   ACMR 2020-12-31  2020  12  3     47
AAPL   2020-12-31   AAPL 2020-12-31  2020  12  3     47
NVDA   2020-10-31   NVDA 2020-10-31  2020  10  3     47
...                  ...        ...   ...  .. ..    ...
VIAV   2020-12-31   VIAV 2020-12-31  2020  12  3     47
WISA   2020-12-31   WISA 2020-12-31  2020  12  3     47
REFR   2020-12-31   REFR 2020-12-31  2020  12  3     47
LSXMB  2020-12-31  LSXMB 2020-12-31  2020  12  3     47
LILAK  2020-12-31  LILAK 2020-12-31  2020  12  3     47

[4556 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2021-03-31   SABR 2021-03-31  2021  3  0     48
ADBE   2021-02-28   ADBE 2021-02-28  2021  2  0     48
ACMR   2021-03-31   ACMR 2021-03-31  2021  3  0     48
AAPL   2021-03-31   AAPL 2021-03-31  2021  3  0     48
NVDA   2021-01-31   NVDA 2021-01-31  2021  1  0     48
...                  ...        ...   ... .. ..    ...
VIAV   2021-03-31   VIAV 2021-03-31  2021  3  0     48
WISA   2021-03-31   WISA 2021-03-31  2021  3  0     48
REFR   2021-03-31   REFR 2021-03-31  2021  3  0     48
LSXMB  2021-03-31  LSXMB 2021-03-31  2021  3  0     48
LILAK  2021-03-31  LILAK 2021-03-31  2021  3  0     48

[4987 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2021-06-30   SABR 2021-06-30  2021  6  1     49
ADBE   2021-05-31   ADBE 2021-05-31  2021  5  1     49
ACMR   2021-06-30   ACMR 2021-06-30  2021  6  1     49
AAPL   2021-06-30   AAPL 2021-06-30  2021  6  1     49
NVDA   2021-04-30   NVDA 2021-04-30  2021  4  1     49
...                  ...        ...   ... .. ..    ...
VIAV   2021-06-30   VIAV 2021-06-30  2021  6  1     49
WISA   2021-06-30   WISA 2021-06-30  2021  6  1     49
REFR   2021-06-30   REFR 2021-06-30  2021  6  1     49
LSXMB  2021-06-30  LSXMB 2021-06-30  2021  6  1     49
LILAK  2021-06-30  LILAK 2021-06-30  2021  6  1     49

[5150 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2021-09-30   SABR 2021-09-30  2021  9  2     50
ADBE   2021-08-31   ADBE 2021-08-31  2021  8  2     50
ACMR   2021-09-30   ACMR 2021-09-30  2021  9  2     50
AAPL   2021-09-30   AAPL 2021-09-30  2021  9  2     50
NVDA   2021-07-31   NVDA 2021-07-31  2021  7  2     50
...                  ...        ...   ... .. ..    ...
VIAV   2021-09-30   VIAV 2021-09-30  2021  9  2     50
WISA   2021-09-30   WISA 2021-09-30  2021  9  2     50
REFR   2021-09-30   REFR 2021-09-30  2021  9  2     50
LSXMB  2021-09-30  LSXMB 2021-09-30  2021  9  2     50
LILAK  2021-09-30  LILAK 2021-09-30  2021  9  2     50

[5262 rows x 6 columns]
                  ticker    Quarter     y   m  q  group
ticker Quarter
SABR   2021-12-31   SABR 2021-12-31  2021  12  3     51
ADBE   2021-11-30   ADBE 2021-11-30  2021  11  3     51
ACMR   2021-12-31   ACMR 2021-12-31  2021  12  3     51
AAPL   2021-12-31   AAPL 2021-12-31  2021  12  3     51
NVDA   2021-10-31   NVDA 2021-10-31  2021  10  3     51
...                  ...        ...   ...  .. ..    ...
VIAV   2021-12-31   VIAV 2021-12-31  2021  12  3     51
WISA   2021-12-31   WISA 2021-12-31  2021  12  3     51
REFR   2021-12-31   REFR 2021-12-31  2021  12  3     51
LSXMB  2021-12-31  LSXMB 2021-12-31  2021  12  3     51
LILAK  2021-12-31  LILAK 2021-12-31  2021  12  3     51

[5327 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
SABR   2022-03-31   SABR 2022-03-31  2022  3  0     52
ADBE   2022-02-28   ADBE 2022-02-28  2022  2  0     52
ACMR   2022-03-31   ACMR 2022-03-31  2022  3  0     52
AAPL   2022-03-31   AAPL 2022-03-31  2022  3  0     52
NVDA   2022-01-31   NVDA 2022-01-31  2022  1  0     52
...                  ...        ...   ... .. ..    ...
VIAV   2022-03-31   VIAV 2022-03-31  2022  3  0     52
WISA   2022-03-31   WISA 2022-03-31  2022  3  0     52
REFR   2022-03-31   REFR 2022-03-31  2022  3  0     52
LSXMB  2022-03-31  LSXMB 2022-03-31  2022  3  0     52
LILAK  2022-03-31  LILAK 2022-03-31  2022  3  0     52

[5243 rows x 6 columns]
                  ticker    Quarter     y  m  q  group
ticker Quarter
ADBE   2022-05-31   ADBE 2022-05-31  2022  5  1     53
NVDA   2022-04-30   NVDA 2022-04-30  2022  4  1     53
ADI    2022-04-30    ADI 2022-04-30  2022  4  1     53
AMAT   2022-04-30   AMAT 2022-04-30  2022  4  1     53
AMBA   2022-04-30   AMBA 2022-04-30  2022  4  1     53
...                  ...        ...   ... .. ..    ...
HOV    2022-04-30    HOV 2022-04-30  2022  4  1     53
LEN    2022-05-31    LEN 2022-05-31  2022  5  1     53
TOL    2022-04-30    TOL 2022-04-30  2022  4  1     53
FOR    2022-06-30    FOR 2022-06-30  2022  6  1     53
STCN   2022-04-30   STCN 2022-04-30  2022  4  1     53

[312 rows x 6 columns]

KeyError: "['QUBT' 'LCFY' nan 'UTME' 'OST' 'SMR'] not in index"

KeyError: "['QUBT' 'LCFY' nan 'UTME' 'OST' 'SMR'] not in index"

In [213]:
class Setup(Ratios):
    
    # getUniverse
    # Function to generate the list of tickers to use as a Universe of stocks to consider
    def getUniverse():
        tickersbs = Ratios.balanceq.index.get_level_values(0)
        tickersinc = Ratios.incq.index.get_level_values(0)
        tickerscf = Ratios.cfq.index.get_level_values(0)
        
        utilities = Ratios.sectorTickers('Utilities')
        financials = Ratios.sectorTickers('Financials')
        
        universe = set(tickersinc).intersection(set(tickersbs)).intersection(set(tickerscf))
        universe = universe - set(utilities) - set(financials)
        
        # also remove tickers for which we currently have no prices...
        prices = Ratios.prices.index.get_level_values(0)
        universe = universe.intersection(set(prices))
        
        # ...and for testing just limit to a small handful of stocks because, you know...
        tech = Ratios.industryTickers('Internet Services')
        universe = universe.intersection(set(tech))
        
        return list(universe)
    
    # writeData
    # Pass in a function to perform on all tickers - executes the function and writes the result directly to a file
    # Means we shouldn't need to keep running the expensive calculations many times (though consider if universe has changed)
    def writeData(fn):
        universe = Setup.getUniverse()
        data = fn(universe)
        data.index.name = 'Quarter'
        fnname = fn.__name__
        data.to_csv(f'MT/mf-{fnname}.csv')

    # Initialisation - this should not need to be called again, just storing in the class as a record of what's been done
    def init():
        print('Calculating/writing Earnings Yield')
        Setup.writeData(Ratios.earningsYield)
        print('Calculating/writing ROC')
        Setup.writeData(Ratios.ROC)

Setup.writeData(Ratios.ROC)

In [ ]:
# MAGIC FORMULA
#
# https://einvestingforbeginners.com/return-on-capital-daah/
#
# The only item not available from MT is in the Working Capital sum
# Liabilities are not broken down very well in MT - so can only really use total Current Liabilities in the Working Capital part
# This might not be so bad as long as it applies to all companies - might be slightly off...
#
# Net Fixed Assets: propertyPlantEquipment (have to ignore depreciation as we don't have this)
# Working Capital: Some assets - Some liabilities
# Some assets: Accounts receivable + Inventories + Other current assets
# 
# Some liabilities: Accounts Payable + Income Taxes payable + Accrued Compensation + Deferred Revenue + Other current liabilities
#

# Not sure if the results from MT are any good, but perseverse for now assuming the numbers are ok
# It seems like its also possible to be more vague with the calculations
#
# eg Following a youTube tutorial - he uses ROA instead of ROC so that's immediately a far simpler approach
#
# THE MAGIC FORMULA:
# Generate a score for the earnings yield (value) and the return on capital (quality)
# Exclude Utilities and Financials
# Exclude foreign stocks (I think I already am)
# Exclude P/E < 5 - seems that these might be weird or low data-quality just remove
# Exclude recent earnings eg within one week
# Create a value rank and a quality rank then combine (how?) ADD THE RANKS TOGETHER.
# Buy top stocks either in one lump or occasionally every 2-3 months
# Hold for at least one year - periodically balance...

In [196]:
# Magic Formula class
# Contains all the functions required to run the Magic Formula over our Universe of tickers
# Call Setup.getUniverse() for the current ticker Universe
class MF():
    
    # Read source data files for the data we need
    ey = pd.read_csv('MT/mf-earningsYield.csv', parse_dates=['Quarter']).set_index('Quarter').sort_index()
    roi = pd.read_csv('MT/mf-ROI.csv', parse_dates=['Quarter']).set_index('Quarter').sort_index()

    # rankGroup
    # For a given group of tickers, representing a single quarter, generate a series ranked in order highest to lowest
    def rankGroup(g):
        collapse = g.sum(axis=0, min_count=1)
        removenas = collapse.dropna()
        ranked = removenas.sort_values(ascending=False).reset_index().reset_index().rename(columns={'level_0':'rank', 'index':'ticker',0:'metric'})
        return ranked

    # backTest
    # Run a full test on the data using fixed MF calculations
    def backTest():
        
        # First for earnings yield
        year = ey.index.year
        month = ey.index.month
        quarter = (month-1)//3
        group = 4*(year - 2009) + quarter

        eyres = ey.groupby(group, axis=0).apply(rankGroup)
        #return eyres
    
        # Similar for ROIC
        year = roi.index.year
        month = roi.index.month
        quarter = (month-1)//3
        group = 4*(year - 2009) + quarter

        roires = roi.groupby(group, axis=0).apply(rankGroup)
        return roires

In [214]:
ey = pd.read_csv('MT/mf-earningsYield.csv', parse_dates=['Quarter']).set_index('Quarter').sort_index()
roc = pd.read_csv('MT/mf-ROC.csv', parse_dates=['Quarter']).set_index('Quarter').sort_index()

In [215]:
year = ey.index.year
month = ey.index.month
quarter = (month-1)//3
group = 4*(year - 2009) + quarter

eyres = ey.groupby(group, axis=0).apply(rankGroup)
sample = eyres.loc[6]

m,s = (sample.mean(), sample.std())
m, s
sample

    rank ticker     metric
0      0   WHLM  46.730852
1      1   TAOP  21.285210
2      2   SOHU  12.021586
3      3  GOOGL   7.001256
4      4   HSTM   6.927263
5      5   MLKN   6.323679
6      6   LPSN   3.550554
7      7   AKAM   2.681625
8      8   BIDU   1.401965
9      9   MCHX  -2.915655
10    10   GIGM -22.778338
11    11   SIFY -24.091077

In [219]:
# Repeat above for ROI
year = roi.index.year
month = roi.index.month
quarter = (month-1)//3
group = 4*(year - 2009) + quarter

roires = roi.groupby(group, axis=0).apply(rankGroup)
roires.loc[3]

   rank ticker     metric
0     0   TAOP  18.937151
1     1   MLKN  12.384909
2     2   HSTM   9.883204
3     3   BLIN   4.365001

In [217]:
# Repeat above for ROC
year = roc.index.year
month = roc.index.month
quarter = (month-1)//3
group = 4*(year - 2009) + quarter

rocres = roc.groupby(group, axis=0).apply(rankGroup)
rocres.loc[7]

   rank ticker       metric
0     0   TAOP  3128.310945

In [221]:
# We now have eyres and roires calculated - add ranks together for each ticker
# Ticker must appear in both otherwise it should be dropped
ey1 = eyres.loc[3]
roi1 = roires.loc[3]
merge = ey1.merge(roi1, how='inner', on='ticker')
merge['finalRank'] = merge['rank_x'] + merge['rank_y']
final = merge.sort_values(by='finalRank')
len(final)

4